### ISSUE TITLE
Getting error saying that - SampleClient.exe is missing while debugging

### ISSUE THREAD

**Issue by bvkudupa** [microsoft/Analysis-Services#1]
Hi,

Thanks for the code, whilst running the code for Azure analysis service, I keep getting the error saying that SampleClient.exe is missing.. Can you please help here.

**Comment by christianwade** [comment]
HI, sorry for the late reply. I think this happens when the references are missing. They need to be set by the build as described at the bottom of this page: https://github.com/Microsoft/Analysis-Services/tree/master/BismNormalizer
