### ISSUE TITLE
Could not load file or assembly Newtonsoft.Json

### ISSUE THREAD

**Issue by PhilAZ** [microsoft/Analysis-Services#10]
I cannot  Start the comparator. I get an error Could not load file or assembly Newtonsoft.Json

**Comment by Geraldziu** [comment]
i second that

**Comment by PhilAZ** [comment]
I was actually able to start comparison using VS Studio 2017 but not VS Studio 2015

**Comment by Geraldziu** [comment]
True, after update to VS Data Tools 2017 it's working fine. Any idea how to block VS from update to the latest version or install last working version of the extension?

**Comment by Geraldziu** [comment]
v.25 is working with VS 2015 Data Tools 👍
