### ISSUE TITLE
BPA Rules Feature suggestion - filter on severity

### ISSUE THREAD

**Issue by YinnWong** [microsoft/Analysis-Services#101]
Currently, the Best Practice Analyzer rules can be in diff severity. sev-3 could cause error/perf issue.  It will be extremely useful to have  a simple filter feature (group by) on their severity, so it can allow developers to prioritize rules and manage their corresponding fix actions.

**Comment by m-kovalsky** [comment]
Hi, thank you for your suggestion. This request is for the Best Practice Analyzer tool itself - not the rules. Please request an enhancement on Tabular Editor's GitHub issues list:

https://github.com/otykier/TabularEditor/issues
