### ISSUE TITLE
ALM toolkit: Lineagetag makes all measures seem changed

### ISSUE THREAD

**Issue by infused-kim** [microsoft/Analysis-Services#102]
Hi,

there seems to be a new property I haven't seen in the past `lineageTag` and it seems to change from time to time in all measures. This causes ALM toolkit and tabular editor to show all measures as changed.

This makes version control extremely difficult.

Is there a way to ignore this property in ALM toolkit?

Thanks, Kim

**Comment by gisnicholas** [comment]
I'm having this issue as well. I just setup deployment pipelines and now my model has these lineage tags everywhere and ALM is seeing every table and measure as changed. I can't find a way to ignore them.

**Comment by infused-kim** [comment]
For now I have solved the issue with a python script that removes the `lineageTag` and `annotations` keys in exported JSON files.

I am using it with the JSON files generated by Tabular Editor, but it could work with the files exported by ALM toolkit too.

You can find the script here:
https://gist.github.com/infused-kim/915c9131d39f9301444362f555318bc7

**Comment by otykier** [comment]
Tabular Editor users face the same issue when saving metadata as a .bim or folder structure for Version Control purposes (see https://github.com/otykier/TabularEditor/issues/819).

1) Is it expected that LineageTag values should change as described in this thread?
2) In general, where can we find more information/documentation on the LineageTag property and its purpose?

Thanks!

**Comment by loancea** [comment]
We are also facing same issue, so would be very useful to find a way to ignore these!

**Comment by christianwade** [comment]
As reported, there is an open bug to fix this on the Desktop team. It seems the LineageTag values are not stable. Once stabilized, having synced the LineageTags one time, they should not keep coming up in the comparison unless they really changed. If issues persist even with the Desktop fix, it's not difficult for me to introduce an option to ALM Toolkit to ignore these at least for comparison purposes. Do you want to see if the Desktop fix works (and in the meantime maybe use Kim's workaround) and then let me know if still need to introduce an ignore option?

**Comment by infused-kim** [comment]
I think since ALM Toolkit is used primarily for comparison and merging it would be good to have an ignore option. I can't imagine anyone ever actually wanting to see the changes of the lineage tags.

And currently it makes ALM Toolkit unusable for anyone who has updated Power Bi, since now all measures show up as changed.

**Comment by jwademcg** [comment]
Would rolling back to a previous version of Power BI Desktop work as a work around?  I guess that is a private repo for Desktop issues, or can we see those?

**Comment by scrampy** [comment]
@christianwade another scenario in which ignoring certain types of comparisons, including lineageTag which brought me to this discussion, is for those of us who use ALM Toolkit in "other scenarios".  In my case, comparing two different, but related PBIX files, that parallel development tracks, that might never merge, but need to keep some elements in sync.  My workflow is to compare in ALM Toolkit and manually apply changes as required.  Being able to ignore lineageTag would allow me to see only the "relevant" differences.

**Comment by DaveRuijter** [comment]
Hi @christianwade, it would be great to have the proposed ignore option for lineageTag, as @scrampy mentions, there are scenarios where it will be super useful even with Desktop fixed.

**Comment by akhil393** [comment]
Same issue was fixed in Tabulareditor latest release [#TabularEditor/issues/819](https://github.com/otykier/TabularEditor/issues/819 ) with an option of just ignoring lineagetag.

**Comment by christianwade** [comment]
Thanks for the heads up. I'll try to get it fixed soon ...

**Comment by christianwade** [comment]
Sorry for the delayed response. Can you try this release?
https://github.com/microsoft/Analysis-Services/releases/tag/5.0.19

There is an option to ignore lineage tag for comparison purposes
![image](https://user-images.githubusercontent.com/20731873/116768291-5f39d880-a9ea-11eb-9403-e0dfc8f19e15.png)

**Comment by DaveRuijter** [comment]
Works well ✔

**Comment by scrampy** [comment]
This works exactly as required in my scenario.  Thank you for taking the time to consider this change - you've made my day!

**Comment by christianwade** [comment]
Glad it works! Thanks for confirming.
