### ISSUE TITLE
[Performance] Set IsAvailableInMdx to false on non-attribute columns - IsAvailableInMdx no longer exists in Tabular Editor 2.15.2

### ISSUE THREAD

**Issue by notyourninja** [microsoft/Analysis-Services#104]
[Performance] Set IsAvailableInMdx to false on non-attribute columns - IsAvailableInMdx no longer exists in Tabular Editor 2.15.2

https://i.imgur.com/iRycBR2.png

https://i.imgur.com/HmcMJy4.png

**Comment by m-kovalsky** [comment]
Hi, if you are opening Tabular Editor via the External Tools ribbon in Power BI Desktop, you will need to select the following option within Tabular Editor: 

File -> Preferences -> "Allow unsupported Power BI features (experimental)". 

This will then show the full list of properties available to edit. Note that not all changes are officially supported (see the following link)

https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools#supported-write-operations

**Comment by notyourninja** [comment]
Thanks @m-kovalsky! Confirming AvailableInMdx after enabling  "Allow unsupported Power BI features (experimental)".
