### ISSUE TITLE
BismNormalizer distribution channels & package types

### ISSUE THREAD

**Issue by nicolas-2008** [microsoft/Analysis-Services#105]
Are there any plans to introduce an alternative distribution channel or another package types like standalone BismNormalizer.dll, powershell module?
In the scenario when BismNormalizer.exe is used as a command line tool for deployment automation it would be far more convenient to get executable/binaries directly, rather than download and install BismNormalizer extension from Visual Studio Marketplace.

**Comment by christianwade** [comment]
Hi Nicolas, I'd like to get there, just haven't had the time yet ...
