### ISSUE TITLE
Update RLS Rule without changing members, how?

### ISSUE THREAD

**Issue by natolira** [microsoft/Analysis-Services#106]
How can I change a RLS rule without changing the members for each Role in a Power BI Dataset?

**Comment by christianwade** [comment]
ALM Toolkit currently doesn't have this feature. Currently you can skip the whole role, or there is an option to ignore all roles, but there is no option to update a role (RLS/OLS rules) whilst retaining the members.

I can add it to the to-do list when I get the chance :)

Anyone else seen this requirement before? The more the merrier.

**Comment by freddycordeiro** [comment]
> 
> 
> > ALM Toolkit currently doesn't have this feature. Currently you can skip the whole role, or there is an option to ignore all roles, but there is no option to update a role (RLS/OLS rules) whilst retaining the members.
> > I can add it to the to-do list when I get the chance :)
> > Anyone else seen this requirement before? The more the merrier.
> 
> Affirmative, Chris! :)
> It would be great to have this feature.

I agree!!! Its going to help a lot!

**Comment by JonatanTorres** [comment]
> 
> 
> ALM Toolkit currently doesn't have this feature. Currently you can skip the whole role, or there is an option to ignore all roles, but there is no option to update a role (RLS/OLS rules) whilst retaining the members.
> 
> I can add it to the to-do list when I get the chance :)
> 
> Anyone else seen this requirement before? The more the merrier.

I think it will be a great feature! It's a problem that I've had and I'm glad to see that there is other people with this request too.

**Comment by christianwade** [comment]
Thanks all for the feedback. I've raised it's position in my todo list :). Still need to get some time to do it, but I plan on it ...

**Comment by christianwade** [comment]
Done in release 5.0.21. Please try it and let me know.

![image](https://user-images.githubusercontent.com/20731873/118211003-379e3380-b420-11eb-8dfb-4f2f46aff942.png)

**Comment by natolira** [comment]
It Worket perfectly! Obrigado Chris!

The only minor thing that isn´t a issue actually is that after the deploy when you compare the datasets again it keeps accusing Different Definitions on the role due to the difference on members, but the tablePermissions actually updated!

**Comment by JonatanTorres** [comment]
WOW!! You rock, Christian!! Thank you so much!

**Comment by virvett** [comment]
That was fast.
Thanks a lot!

**Comment by freddycordeiro** [comment]
Awesome!!! Thanks a lot!

Em qui., 13 de mai. de 2021 às 23:21, Christian Wade <
***@***.***> escreveu:

**Comment by christianwade** [comment]
You are all welcome! De nada!
