### ISSUE TITLE
ALM Toolkit - Linguistic Schema

### ISSUE THREAD

**Issue by limnerconsulting** [microsoft/Analysis-Services#107]
We deploy changes to datasets in premium workspace using ALM Toolkit. However, the linguistic schema is not loaded to the service on deployment. The synonyms we add in Power BI desktop is not available in service. If we cannot deploy linguistic schema through ALM toolkit, what is the alternative to load this in service? When we try to copy schema contents using Tabular editor, it gives an error. So, how do we load this to service other than publishing the desktop and having to refresh in full the dataset in service again?

**Comment by christianwade** [comment]
Hi, can you please try the latest release 5.0.22 and let me know? Linguistic schema should work now.

**Comment by otykier** [comment]
@limnerconsulting do you mind raising a ticket on [Tabular Editor's GitHub site](https://github.com/otykier/TabularEditor/issues) regarding the error you mentioned, when trying to copy the schema? If you can provide an example .pbix file that reproduces the error, I would greatly appreciate that, thanks!

**Comment by limnerconsulting** [comment]
> Hi, can you please try the latest release 5.0.22 and let me know? Linguistic schema should work now.

Hi Christian...Yes. It works perfectly now. Thank you.

**Comment by limnerconsulting** [comment]
> @limnerconsulting do you mind raising a ticket on [Tabular Editor's GitHub site](https://github.com/otykier/TabularEditor/issues) regarding the error you mentioned, when trying to copy the schema? If you can provide an example .pbix file that reproduces the error, I would greatly appreciate that, thanks!

@otykier  I checked now after the update. The issue is because, when I open the power BI downloaded linguistic schema file in visual studio code, it is not opening with the proper json format.
![image](https://user-images.githubusercontent.com/66367870/118794769-8849dc80-b8b7-11eb-912f-6727cda0810a.png)

So, I was copying from VSC and pasting it in Tabular editor. When I copy and paste from ALM toolkit comparison with the proper json format, I am able to paste and save in Tabular editor. So, should I still open a ticket in Tabular Editor GitHub site?

**Comment by otykier** [comment]
@limnerconsulting I see, thanks for clarifying. No need to open a ticket in this case, since Tabular Editor by design only supports the JSON format.
