### ISSUE TITLE
Execute AsPartitionProcessing from SSIS script task

### ISSUE THREAD

**Issue by ihafidh** [microsoft/Analysis-Services#11]
The documentation states that the sample "Can be leveraged in many ways including from an SSIS script task". Is there sample code where you can run the AsPartitionProcessing process using an SSIS script task? 

The only way that I was able to run the AsPartitionProcessing process in SSIS is by invoking the "AsPartitionProcessing.SampleClient.exe" file. However, running an exe in SSIS has limitations such as error handling. For example, the Tabular might have errors (which are logged in the database) but the SSIS task thinks that it ran successfully. 

It would be nice to have a sample code where you can run the AsPartitionProcessing process using an SSIS script task.

**Comment by Geraldziu** [comment]
I'm using AsPartitionProcessing.SampleClient.exe from DB Job and made a workaroud for the issue with errors during the processing. First step is to run the EXE. Secund step is to run this t-sql
`EXEC [dbo].[usp_LastProcessingLogs] @ErrorsOnly = 1
If @@ROWCOUNT > 0 RAISERROR ('Procesing error', 16, 1)`
When the second step ends with error - send email. Of course model is set to retry 10 times with 60 sec deley. So the error means that something needs human attatntion.

**Comment by ihafidh** [comment]
Thanks Geraldziu. That's a good workaround.
