### ISSUE TITLE
[DAX Expressions] Inactive relationships that are never activated	

### ISSUE THREAD

**Issue by fbouckae-crm** [microsoft/Analysis-Services#110]

**Comment by fbouckae-crm** [comment]
I get this message on my model but the inactive relations are activated through Calculation Groups, when the end-user selects the Calculation Item
Are these taken into account ?

**Comment by fbouckae-crm** [comment]
also related to calculation groups/Items

**Data columns must have a source column**, on Calculation Group Colums

**Comment by christianwade** [comment]
Adding @m-kovalsky

**Comment by m-kovalsky** [comment]
Thanks for raising this. The scope of the rule regarding inactive relationships has been expanded to include Calculation Items in Version 1.1.1.

As to Calculation Group Columns having source columns - there is no separate class for Calc Group Columns. They are treated as Data Columns within the Tabular Object Model. Therefore, if a Calc Group Column does not have a source column it will be caught by the current rule's existing logic.
