### ISSUE TITLE
ALM toolkit could not load PBIX which has a live connection to Power BI online dataset

### ISSUE THREAD

**Issue by sdg002** [microsoft/Analysis-Services#112]
Hi All,
I am using the `5.0.22` version of the `ALM Toolkit` to compare 2 PBIX files.

The PBIX files are developed around a Power BI online dataset and the files differ by a couple of measures only.

Some challenges:
- ALM Toolkit does not show PBIX as a file option
- Upon clicking the `Compare` button, the tool displayed the following error (Not very helpful)
![image](https://user-images.githubusercontent.com/20245330/119868533-0db43900-bf17-11eb-9941-29186af72981.png)
- I tried exporting the PBIX to PBIT and then using `ALM Toolkit`. But , the error continued.

In the past, I have used `ALM Toolkit`  for PBIT files and has worked really well.

Any suggestions?

Thanks,
Sau

**Comment by christianwade** [comment]
Hi Sau,

Power BI Desktop does not support accessing the PBIX file contents because this could result in corruption of the file. We want Desktop to support this but it's not there yet.

It should work with PBIT files. Please confirm you saved as PBIT through the menu system. If still doesn't work and you are able to send me the files, I'd gladly try to reproduce on my environment.

Christian

**Comment by sdg002** [comment]
[powebi-alm.zip](https://github.com/microsoft/Analysis-Services/files/6557006/powebi-alm.zip)

Hello @christianwade ,

Thanks for looking into this. I have attached 4 files.
- `alm-demo.pbix`  and `alm-demo-copy.pbix` are the original PBIX files which were created by using data from an online Power BI Dataset.
- `alm-demo.pbit`  and `alm-demo-copy.pbit`  were created from the respective `PBIX` files by using the `Export` menu option of `Power BI`

I was unable to get `ALM Toolkit` to diff with 
the pair `alm-demo.pbix`  and `alm-demo-copy.pbix`  
and 
the pair `alm-demo.pbit`  and `alm-demo-copy.pbit`

What am I doing wrong here?  


Regards,
Sau

**Comment by christianwade** [comment]
Hi Sau, I think these are live connect PBIX / PBIT files. This means they do not contain the dataset, only the report. ALM Toolkit requires the dataset. So I believe you need the PBIX that originally created the dataset.

**Comment by christianwade** [comment]
Hi Sau, this is a legit request, but the Power BI interactive reports do not support a standardized metadata format right now, which prevents community tools from building this type of functionality. We (the Power BI product group) would like to support standardized metadata format for all artefacts (e.g. dataflows, dashboards ...) one day don't have a timeline right now. All I can suggest is to keep lobbying for it, for example at ideas.powerbi.com

**Comment by sdg002** [comment]
Understood. There is no formal tool at the moment.

Please help me out. What happens if I unzip the file?  Which specific file would contain the DAX expression(s)?

All I need is - 
`What were the new DAX expressions added?`
`Which DAX expression underwent some change?`


Right now - the only option is to open the 2 PBIX side by side.

Thank you.

**Comment by christianwade** [comment]
I wouldn't know. PBIX file contents are undocumented (and unsupported). They change the structure and I suspect the contents are stored differently to the last time I looked.
