### ISSUE TITLE
Importing Best Practice Rules fails for Tabular Editor 3 -- wrong folder name

### ISSUE THREAD

**Issue by andrewtuplin** [microsoft/Analysis-Services#114]
I tried to import the best practice rules via C# and it failed. My investigation found that the script was expecting to find a folder in AppData called TabularEditor but only a folder called "TabularEditor3" exists.  I presume this will be an issue for anyone who didn't have  previous versions of TabularEditor installed.

**Comment by m-kovalsky** [comment]
Thanks for raising the issue. I've updated the script on GitHub (https://github.com/microsoft/Analysis-Services/tree/master/BestPracticeRules#setup-automated) accordingly. Also updated the manual setup steps for parity.
