### ISSUE TITLE
ALM Toolkit update error: The following syntax error occurred during parsing: Invalid token

### ISSUE THREAD

**Issue by larsfisker** [microsoft/Analysis-Services#115]
Hi, 
I am experiencing this error when trying to update my target model. There are no validation errors when running the validation. 

![ALM Toolkit error](https://user-images.githubusercontent.com/86651434/123756901-b01c5f00-d8bd-11eb-8cb8-8864d66f5db5.PNG)

I can locate, what I think is the error, when looking at the generated script, but I do not know to debug it. 

Hope you can help. 

Best regards

**Comment by christianwade** [comment]
Hi, I'd like to get more info on this and try to repro it. Can you send me anything like the necessary files to repro it?
