### ISSUE TITLE
Deadlock issues

### ISSUE THREAD

**Issue by LaguideHalid** [microsoft/Analysis-Services#116]
I have just implemented Christian Wade's "Automated Partition Mangement" solution in my company.
https://azure.microsoft.com...

But I got an error message when I run the process full of all tables.

I have this error message
`Exception message: Failed to save modifications to the server. Error returned: 'The operation was canceled because a deadlock condition was detected with another transaction. This usually occurs when two transactions need to lock the same objects, but do so in a different order. Please retry your operation.
`
Anyone know how to fix this problem?

**Comment by christianwade** [comment]
Hi, I'd start by making sure you are using the latest client libraries from here: https://docs.microsoft.com/en-us/analysis-services/client-libraries?view=asallproducts-allversions#amo-and-adomd

Deadlocks often occur when multiple operations such as refreshes and queries are occurring at the same time. The accompanying whitepaper with the Automated Partition Management has a section on it with the timeout settings you can use to control this

**Comment by LaguideHalid** [comment]
Hello @christianwade 

Thank you for your help.

It's really strange because there is no query on this tabular model.
It's a new model that is being tested and that no one is using.

This model is deployed on Azure Analysis Service and I use the solution with Azure functions to process it.

As you advised me, I configured the table [TableConfiguration]. 
The values ​​for the CommitTimeOut are 100,000 to avoid the lock.
And when I process the tables manually I don't get any errors.

Do you have any idea to help me resolve this error?

**Comment by LaguideHalid** [comment]
Hello

Another thing that I weird is that when I run the solution locally, on my personal workstation and not on Azure, I don't get any errors.
It drives me crazy. Three days that I have been working on this error.

**Comment by christianwade** [comment]
Are you using the latest client libraries NuGet in the solution and rebuilt/redeployed?

**Comment by avijit1804** [comment]
@christianwade Any update on this ?
facing similar issue .

@LaguideHalid Did you issue resolved ?

**Comment by christianwade** [comment]
Locking and blocking is something you may have to deal with if you have metadata, refresh and/or queries running concurrently. This is not specific to this tool. There are various settings and optimizations you can consider. Some are discussed briefly on page 26 of [this document](https://github.com/microsoft/Analysis-Services/blob/master/AsPartitionProcessing/Automated%20Partition%20Management%20for%20Analysis%20Services%20Tabular%20Models.pdf), and others.
