### ISSUE TITLE
Feature Request: ALM Toolkit support for Tabular Editor serialized models

### ISSUE THREAD

**Issue by jasonhendrix** [microsoft/Analysis-Services#117]
Tabular Editor allows you to serialize a model so that it is stored as several JSON files in several folders.  This allows for better integration with source control.  More information on that process is here: https://docs.tabulareditor.com/Advanced-features.html#folder-serialization

However, to use that option along with ALM Toolkit requires that you first take an additional step to convert back to a single .bim file.  It would be nice to be able to skip that step.

To do so, I am hoping that ALM Toolkit could add a feature so that the serialized model version that Tabular Editor creates could be used as a source and destination for comparisons.

**Comment by christianwade** [comment]
Thanks for the feedback. I'll keep it in mind!

**Comment by jspanos71** [comment]
This would be a huge help! +1

**Comment by jasonhendrix** [comment]
FYI - I have posted a similar request to the Tabular Editor team: https://github.com/TabularEditor/TabularEditor/issues/894

**Comment by jasonhendrix** [comment]
FYI - I have submitted a pull request to Tabular Editor to help with this issue: https://github.com/TabularEditor/TabularEditor/pull/896

**Comment by christianwade** [comment]
Upcoming TMDL serialize to folder should do the trick 😉
