### ISSUE TITLE
Feature request: Possible to filter "Object Type" when comparing models with ALM Toolkit?

### ISSUE THREAD

**Issue by jobosol** [microsoft/Analysis-Services#118]
Hi, 
It would be very helpful to filter on the "Type" field when comparing models. 

For example if I only want to compare "Measures" between two models and ignore the other differences I could put a filter on type = measure. 

If this is already possible please point me in the right direction for how to do this.

**Comment by christianwade** [comment]
Sorry I missed this. This is not planned, but will keep it in mind!
