### ISSUE TITLE
Issue: unable to resize the lower section 

### ISSUE THREAD

**Issue by CareVenture** [microsoft/Analysis-Services#119]
Hi Christian,

Just installed v5.0.23.  First of all, thank you for creating this tool.  I will definitely use it quite a bit.  It is great!

One issue, I am not able to adjust the height of the bottom section where I can view the JSON code.  It seems the ALM tool is not capturing my Windows size properly.   

I was not able to find any similar reported issue.  However, I was able to reproduce the problem consistently (eg restart, try different PBI files, etc)

Attached below is a screenshot. 
![ALM tool issue](https://user-images.githubusercontent.com/30349578/128645640-141dc4dc-8c4f-4515-b01c-ea2d4ee0f68e.png)

**Comment by samaguire** [comment]
Yeah - I get the same issue. It's like the JSON pane doesn't stick to the lower boundary of the window when the window goes beyond a certain height.

**Comment by christianwade** [comment]
Hi all, thanks for raising this! I noticed it a while back myself and I agree it's not the optimal experience. The differences grid and JSON diff control is typescript based and created by MAQ Software (hence their logo is shown). Unfortunately, typescript is not my area of expertise, so it is more difficult than usual to get this fixed (MAQ Software's engagement was on a limited time basis). However, I will ask for it at the first opportunity!
Christian

**Comment by fl28882** [comment]
Hi all.

Is there an update on this topic?

I am working with a very large model and would love to see this window sizing issue fixed soon.
I am also facing general performance issues (mostly loading the lower section comparison & scrolling in it).

Thank you for your feedback.

____________
Version 5.0.31

**Comment by christianwade** [comment]
I don't want to count my chickens but I think another contributor is fixing it. Please give me a week or so to confirm ...

**Comment by christianwade** [comment]
Should be fixed now in release 5.0.32!

**Comment by samaguire** [comment]
Working for me. Nice one! 👏

**Comment by fl28882** [comment]
Looks good, thank you! This helps us a lot.
