### ISSUE TITLE
More detailed instruction on how to get SampleClient to work with Azure function

### ISSUE THREAD

**Issue by baatch** [microsoft/Analysis-Services#12]
Hi,

First of all I want to just say that this solution is awesome! I have done every example in the whitepaper and got everything to work locally. Now it is time to get the Sample client to work in an Azure Function, but I find that there is not much detail about how to go about that. Many don't have coding background and it would help alot if there was an step by step for getting the SampleClient up and running in an Azure Function. I don't even know where to start. Can I just copy and paste the code from SampleClient to an Azure function?

I have followed the other blogs, (https://azure.microsoft.com/en-us/blog/azure-as-automated-partition-management/?v=17.23h
https://sqldusty.com/2017/06/21/how-to-automate-processing-of-azure-analysis-services-models/)
that have instructions for how to process the Azure Analysis services through an Azure Function and got that to work. But I want to get the SampleClient solution to work through Azure function.

If anyone can point me in the right direction it would be very helpful.

**Comment by christianwade** [comment]
Hi, would like to add a section on that - just a matter of time :)

You would have to upload the AsProcessing dlls to Azure Functions like [here](https://blogs.msdn.microsoft.com/benjaminperkins/2017/04/13/how-to-add-assembly-references-to-an-azure-function-app/), but you can avoid uploading the TOM ones if you use the NuGet references like [here](http://blogs.adatis.co.uk/ustoldfield/post/Tabular-Automation-and-NuGet). Then copy the relevant parts of the SampleClient code to the Azure Function. You can refer to a SQL db for the configuration/logging

**Comment by baatch** [comment]
Thanks for replying @christianwade with the tips. Unfortunately I'm still to inexperienced with C# to setup Azure Function by "copy the relevant parts of the SampleClient code". 

So I took another route. I got some help from a developer colleague that suggested that the easiest and fastest way was to deploy the SampleClient is to use Azure Webjobs. It basically was right click in VS on SampleClient project and "Publish as Azure Webjob" and following the wizard. After a few minutes I had a working solution. Much much easier. @christianwade maybe you can consider adding Azure Webjobs as an option in the whitepaper?

When deploying the Azure webjob from VS it was not possible to create a scheuled CRON timer through the wizard for the Azure webjob, so I had to create a file called settings.job in the root of the project with the CRON expression for the scheduled to be run. For more info on how to create the file check: https://blogs.msdn.microsoft.com/tfssetup/2016/05/18/deploying-and-schedule-azure-webjobs-from-vsts-to-azure-web-app-with-bonus-cron-scheduling/


Hopefully this tip can help any others that are also struggling with the Azure Function part.

**Comment by byobi** [comment]
@baatch - very interesting (re: webjobs)... as a fellow .NET n00b, i was completely unaware of this feature.

If you ever decide to switch back to Azure Functions, you may find [this blog post](http://byobi.com/2018/03/implementing-as-partition-processing-via-azure-functions/) helpful. 

Afraid I'd been sitting on it for a while now and seeing these comments popup in my inbox reminded me that I still needed to publish the post.

**Comment by baatch** [comment]
@byobi GREAT blog post! Exactly what I needed, I'm going to try it out. Thanks for helping out a fellow .NET n00b =) !

**Comment by m1nkeh** [comment]
@baatch , @byobi - Azure Functions is *basically* webjobs mk2, if you look at the azure fuctions nuget package they also leverage the webjobs / webjob extensions one.. if you are doing new development i would recommend functions over webjobs... not that there is anything really wrong with a webjob they aim to solve the same problem... but functions are an iteration again..

of course, you can still deploy azure functions from visual studio, just as you can webjobs ;)

good comparison: https://stackify.com/azure-webjobs-vs-azure-functions/

**Comment by christianwade** [comment]
Fantastic work @byobi !! 🥇 
Comments from @m1nkeh align with my understanding
@baatch glad you're up and running 👍
