### ISSUE TITLE
URL for Workspaces

### ISSUE THREAD

**Issue by MBStandard** [microsoft/Analysis-Services#122]
I am working around a 'Cannot connect to database' error.
I click the Compare button, and I want to load a Source with content in my Premium workspace.  
What is the format string that I type in the 'Workspace' item, under Dataset.  I know the URL to my workspace(s) but am having trouble getting this tool connected.

**Comment by christianwade** [comment]
Sorry I missed this. Please reopen if still an issue and we can debug. For example, review the format you're using.
