### ISSUE TITLE
erroring out with dataset size limitation with schema compare in ALM tool kit

### ISSUE THREAD

**Issue by NishanthVootukooru** [microsoft/Analysis-Services#125]
Hi ,

I have been successfully using ALM toolkit for a while. But recently i am facing an issue with Schema compare when i am trying to compare a huge dataset published on to premium workspace.

"Unable to load the dataset: its size of 2224 MB exceeds the limit of 2048 MB. If the dataset is hosted on a PowerBi Premium capacity, you may also reach out to your capacity administrator to see if the limit can be adjusted"

Can someone please help me with this error.

**Comment by christianwade** [comment]
Hi Nishanth, I think this is unrelated to ALM Toolkit. Can you check the capacity settings?
https://powerbi.microsoft.com/en-us/blog/capacity-settings-for-datasets-are-now-in-power-bi-premium-gen2/
