### ISSUE TITLE
Options page is not displayed completely

### ISSUE THREAD

**Issue by guruprasadwestrac** [microsoft/Analysis-Services#126]
Hi,
I see Options page is cut off, I am not able to see Database Deployment. 
![image](https://user-images.githubusercontent.com/54703518/144754288-8677f309-7a68-4afe-84d6-0e4d383dcc0e.png)

**Comment by Esk96** [comment]
Any updates to this issue? I face the same. Deploying without those options processes all the (non-affected) tables too.

**Comment by christianwade** [comment]
Thanks for raising. Looking into it ...

Did this start around Nov 19th? I did a release that added a new option to retain refresh policies that could have affected Winforms HDPI resizing

**Comment by christianwade** [comment]
Can you please try this version out to confirm it works for you before I publish it. DPI issues are difficult to repro. Can you please ping me at 
![image](https://user-images.githubusercontent.com/20731873/148433292-a6f189fd-6839-449d-aca3-18410ee70d2a.png)
?

**Comment by Esk96** [comment]
Did so👍..

**Comment by Esk96** [comment]
Unfortunately, don't know when the issue exactly started, I observed it this week.
