### ISSUE TITLE
AlmToolkit is not DPI-aware

### ISSUE THREAD

**Issue by samusaran** [microsoft/Analysis-Services#128]
The current version of ALM Toolkit (5.0.24) and previous versions are not DPI-aware. That means that on displays not set to 100% scaling, the text is blurry and difficult to read.

Given that the application is a Windows Form app, it would be trivial to enable this feature.

**Comment by christianwade** [comment]
Sorry for the delayed response. Various DPI fixes have been introduced over the past few years. The next/upcoming release will have more fixes. Please reopen if still persists.
