### ISSUE TITLE
ALM tool can update a XMLA end point?

### ISSUE THREAD

**Issue by DanielPiri** [microsoft/Analysis-Services#129]
I am using ALM tool to update two versions of tabular Model. If the final model is an XMLA Conection should do I need any extra version of ALM?? , because free one doesn´t work

**Comment by christianwade** [comment]
Hi Daniel, can you please provide more context? What is the error message you are seeing. There is only 1 version of ALM Toolkit (the free one), and it should work in the scenario you describe.
