### ISSUE TITLE
AsPartitionProcessing with Application Service Principal ?

### ISSUE THREAD

**Issue by baatch** [microsoft/Analysis-Services#13]
Hi, 

Is it possible to use the AsPartitionProcessing with a service principal instead of username password?

**Comment by byobi** [comment]
short answer, yes.

longer answer, to get it working I ended up modifying the solution a bit as well as leveraging an Azure AD library (Microsoft.IdentityModel.Clients.ActiveDirectory.dll)

if you can wait until later in the week, I'll update the previous blog post.

**Comment by baatch** [comment]
@byobi very cool, thanks for contributing. I will wait for your updated blogpost =)

Is is possible to create your Azure function as a Visual Studio project and then deploy to Azure?

**Comment by christianwade** [comment]
Version 15 of TOM from the NuGet package below should work by plugging into the connection string (example below). For certificate based, can use "cert:thumbprint" in place of password
https://www.nuget.org/packages/Microsoft.AnalysisServices.retail.amd64/

string appId = "xxx";
string authKey = yyy";
string connString = $"Provider=MSOLAP;Data Source=asazure://southcentralus.asazure.windows.net/zzz;User ID=app:{appId};Password={authKey};";
Server server = new Server();
server.Connect(connString);

**Comment by byobi** [comment]
that sure does look a lot easier than the path I went down :-(

![image](https://user-images.githubusercontent.com/7781157/38056866-b02a1f16-32ab-11e8-990c-3b6865b9bd14.png)

**Comment by byobi** [comment]
this is definitely outside my wheel-house... what's the difference between your way and the way I'm doing it?

**Comment by christianwade** [comment]
The difference is TOM is dealing with getting the access token. TOM also deals with refreshing it under the covers so it doesn't expire for long running ops

**Comment by byobi** [comment]
good deal.. got it working your way... ty!

**Comment by christianwade** [comment]
Np!

**Comment by baatch** [comment]
Any updates on any blogs @byobi or @christianwade :) ?

**Comment by byobi** [comment]
@baatch - updates on what?

**Comment by baatch** [comment]
@byobi sorry for not checking your blog, it was already updated! 
http://byobi.com/2018/04/implementing-as-partition-processing-via-azure-functions-part-2/

I'm going to check it out immediately, thanks alot :) !!

**Comment by baatch** [comment]
@byobi  your fork repo is missing the AsPartitionProcessing.SampleAzureFunction project.

**Comment by byobi** [comment]
@baatch - good to go now...

**Comment by baatch** [comment]
@byobi finally got it working in my environment with your Function sample! Thanks alot for sharing :)

**Comment by byobi** [comment]
@baatch - awesome, glad I could help!
