### ISSUE TITLE
Async Power BI dataset Refresh :: Unable to get refreshid / requestid

### ISSUE THREAD

**Issue by debashish10** [microsoft/Analysis-Services#130]
I was trying to test Power BI Dataset refresh using the recently announced preview documented here: https://docs.microsoft.com/en-us/power-bi/connect-data/asynchronous-refresh .

**Sample Powershell code** 

function Facts() {
  
    $fact_jsonscript = '{
    "type": "clearValues",
    "retryCount" : 2,
    "objects": [
      {
        
        "table": "Fact_Action",
        "partition":"201812"
      }
    ]
  }'

    return $fact_jsonscript

}

$Clear_Json = Facts

$AADSynceStatusRESTAPIURI='https://api.powerbi.com/v1.0/myorg/groups/"workspaceid"/datasets/"datasetid"/refreshes'

$refreshId =Invoke-RestMethod -Uri $AADSynceStatusRESTAPIURI -Headers $authHeader -Method Post -Body $Clear_Json
$refreshId.OperationId

$result=Invoke-RestMethod -Uri $AADSynceStatusRESTAPIURI -Headers $authHeader -Method GET 
$result.value

**I am facing two issues:**

1. After running the POST method to trigger the refresh , it is not returning any response which in the case of AAS we could get the refreshid.

2. I am running clear operation for one partition in Fact_Action on which i am getting error on another table instead of Fact_Action  upon checking the power bi service logs .
It looks like body is getting ignored in this case.

Could you please check if i am doing anything wrong here and suggest.

![image](https://user-images.githubusercontent.com/55327056/147244998-2a08e72e-095b-45d3-aa47-0ea5e6ffc724.png)

**Comment by christianwade** [comment]
Sorry I missed this. If still a problem, please raise a CSS ticket as this is a Microsoft CSS supported feature.
