### ISSUE TITLE
Can't make changes to dataset because XMLA read/write support "not enabled" 

### ISSUE THREAD

**Issue by Mardurolla** [microsoft/Analysis-Services#133]
Please add to your documentation where on [Power BI] > ‘Admin portal’ you need to Enable ‘Read/Write’ XMLA Endpoints. Otherwise, your followers may leave your solution in frustration... I wasted a whole week searching before I found the [Setting] solution. 

Steps taken: (1) having previously uploaded dataset onto a PPU Workspace [with Dimond graphic showing]. (2) Then after making two minor changes, I did a Connect with ‘ALM Toolkit for Power BI’ in ‘External Tools’ on Power BI Desktop [MS Store client version]; (3) get a pass on ‘Validate Selection’; you will get following error message when proceeding with ‘Update’

Error:
"It looks like you can't make changes to this dataset. Please contact a capacity administrator to make sure XMLA read/write support is enabled in the capacity settings enable XMLA read/write support capacity settings on the Power BI Premium capacity, and then try again. For additional information, 
see 'XMLA read/write support' in the product documentation. Technical Details: 
Root Activity Id: [remove for security let me know if you need it] Date (UTC): [removed]
"

I am the only User/'Global Admin' on my organization on a MS 365 Premium with 'Power BI per User' account. After an entire week of digging, I found that there is such a thing as a Power BI ‘Admin portal’ [a job in itself to find it as it is under Settings > Admin portal > ‘Premium Per User , which Search won’t find it for you]
https://app.powerbi.com/admin-portal/ppuTenantSettings?language=en-GB  ‘Premium Per User’ subpage. Which is where you enable your XMLA to Read Write
![XMLApbiAdminPortalEpointEnable](https://user-images.githubusercontent.com/75253784/151812410-9f8c2a9e-3a21-46c0-8d04-598b3e2cc91e.png)

**Comment by christianwade** [comment]
Thanks for highlighting this. I'll forward it to the docs team to mention PPU enablement is at the tenant level instead of capacity in the XMLA docs ...
https://docs.microsoft.com/en-us/power-bi/admin/service-premium-connect-tools#enable-xmla-read-write
