### ISSUE TITLE
Feature Suggestion, Select All/Unselect all and CTRL + Click to Bulk update Skip/Update

### ISSUE THREAD

**Issue by koconder** [microsoft/Analysis-Services#136]
For those with huge models, better select/unselect all for the Skip/Update. So you can do a skip all etc. Its super clunky when you need to push one change.

**Comment by christianwade** [comment]
Thanks for the feedback. Have you tried multi-select > Skip or the menu options to skip in bulk?
![MultiSkip](https://user-images.githubusercontent.com/20731873/155447916-913abd54-9d6f-41de-a077-dfcbfa3cdf73.gif)
?

**Comment by koconder** [comment]
I must be blind, ledgend!
