### ISSUE TITLE
Deploy AW sample tabular model fails...

### ISSUE THREAD

**Issue by sherifffruitfly** [microsoft/Analysis-Services#14]
I'm running sql standard 2017 and VS enterprise 2017.

I restored the included AWDW bak file without incident. Solution builds without incident.

Going into the bim within VS, and going to Table Properties on a table, and clicking Design, results in the following connectivity error:

DataSource.Error: Microsoft SQL: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)
Details:
    DataSourceKind=SQL
    DataSourcePath=localhost\sp1;AdventureWorksDW
    Message=A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)
    Number=-1
    Class=20

Error makes sense because my server is localhost, not localhost\sp1.

How do I change the DataSourcePath to correctly reflect my server?

-----------
Deploying the tabular project also fails with the "error 26 locating server/instance specified" message.

Additional VS warnings spring up:
Severity	Code	Description	Project	File	Line	Suppression State
Warning		Found conflicts between different versions of "Microsoft.AnalysisServices.Core" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.	AsPartitionProcessing.SampleClient			

Severity	Code	Description	Project	File	Line	Suppression State
Warning		Found conflicts between different versions of "Microsoft.AnalysisServices.Tabular" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.	AsPartitionProcessing.SampleClient			

So how do I get from here to success with the sample?

thanks for any tips,
sff

**Comment by christianwade** [comment]
Hi, can you try to edit the data source and change the servername to remove "\sp1"? You can access it by opening the .bim file and finding it in the tabular model explorer.

**Comment by sherifffruitfly** [comment]
worked just fine thanks!

with the M method in place for data sourcing, are they gonna give gui access to connection strings? manually editing bim files seems pretty low.

**Comment by christianwade** [comment]
Glad it worked. With the new structured data sources in 1400 models, there is no connection string stored in the model. There should be a UI for editing them in SSDT
