### ISSUE TITLE
Feature request: Enable comparison/update at column level.

### ISSUE THREAD

**Issue by atmisra** [microsoft/Analysis-Services#140]
My issue is that the source model generally has fewer columns than the target (in my scenario, the target is a further-enriched version of the source, a more simplified model)

Since differences are flagged at the table level, it would be very helpful to be able to update metadata at the column level.

**Comment by christianwade** [comment]
Hi, I get this feedback from time to time and I wish I could enable it. Unfortunately it's challenging because of interdependencies between the objects that make up a table. For example, columns depend on partitions. Adding/removing/updating them would be fragile.

**Comment by atmisra** [comment]
Too bad - thank you for providing input.
