### ISSUE TITLE
BPR Rule: Mark primary keys

### ISSUE THREAD

**Issue by Klimkiv** [microsoft/Analysis-Services#148]
What is a rule to mark primary keys in a model? Why is it needed? Please advise!

**Comment by m-kovalsky** [comment]
This doesn't have any particular effect on the model. However, columns marked as primary key columns show in bold within the field list in Tabular Editor (which is helpful for quickly distinguishing such columns). Naturally, this is a rule of lesser priority (as is the case with many of the formatting category rules).

**Comment by Klimkiv** [comment]
Thank you!
