### ISSUE TITLE
Missing assembly

### ISSUE THREAD

**Issue by Geraldziu** [microsoft/Analysis-Services#15]
Hi,

After updating client libraries (AMO, ADMOD, OLEDB) from 14 to 15 AsPartitionPrcessing.SampleClient stoped working with error

Could not load file or assembly 'Microsoft.AnalysisServices.Tabular, Version=14.
0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependenc
ies. The located assembly's manifest definition does not match the assembly refe
rence. (Exception from HRESULT: 0x80131040)

Strange thing is that when i updated the drivers on dev server the drivers are available in version 13, 14 and 15, but when i do that on test server i have only version 13 and 15. Tried to change the version in AsPartitionProcessing.SampleClient.exe.config file from 14 to 15 but that didn't work.

Any workaround? Or permanent fix for using leatest drivers?

**Comment by christianwade** [comment]
Hi, are you using NuGet references from here: https://www.nuget.org/packages/Microsoft.AnalysisServices.retail.amd64/
The NuGet references should work independently of GAC installations (unlike previous versions).

Also can you check the project file whether old references are still there.

**Comment by Geraldziu** [comment]
Well, i build the project about a year ago, with minor change in the code to support username/pass stored in DB, and I have no idea what reference i used then. I barely remember that i had to install client drivers to build the project.
So I should build the latest version? No modifications needed for the user/pass from DB to connect to Azure? Any idea if this issue https://github.com/Microsoft/Analysis-Services/issues/13 will be ever included in this app?

**Comment by christianwade** [comment]
If you have a working version and you can set the new db user/pass in a configuration, and it works, then that is fine.

If you need to recompile, you may need to do something to resolve this. Actually another user had to increase the target .net framework version for the projects to compile after a new TOM version.

Regarding issue #13 , it should work with the NuGet references to v15
