### ISSUE TITLE
Format based on language

### ISSUE THREAD

**Issue by benito2313** [microsoft/Analysis-Services#151]
We have a Enterprise model with multiple languages.
But with that also multiple formatting.
Like the date dd-mm-yyyy for in europe and mm-dd-yyyy in the US.
And also for the decimal and thousand separator with #.##0,00 for europe and #,##0.00 for the US.

Is something like this possible to change when the language changes?
If this is not default behavor, i would like to set it for the language myself.

Also a thing is the currency but this i can fix with a currency table with the symbols.

Kind regards,

Ben

**Comment by christianwade** [comment]
Sorry I missed this. If still persists, please open a CSS ticket as this is core AS behavior.
