### ISSUE TITLE
NetCore - Method ClrAssembly.LoadFiles() is not implemented

### ISSUE THREAD

**Issue by cosminiv** [microsoft/Analysis-Services#158]
Not sure if this is the right place to report this issue, but we have a problem with the package _Microsoft.AnalysisServices.NetCore.retail.amd64_, version 19.42.

The method **ClrAssembly.LoadFiles()** throws a **NotImplementedException**("Assembly reference detection for .NET Core clients is still WIP!")

Do you know when this method will be implemented? And is there a workaround in the meantime?

Thank you.

**Comment by christianwade** [comment]
Sorry I missed this. If problem still persists, please open a CSS ticket as this is core AS functionality.
