### ISSUE TITLE
Unclear on which *direction* actions like Update/Delete etc go?

### ISSUE THREAD

**Issue by seedjay1** [microsoft/Analysis-Services#16]
Hi,

I've been using that other dude's Tabular Editor to make improvements to a deployed tabular model. So now the visual studio bism is behind the good server-deployed model.

I'm hoping to use normalizer to catch-up the visual studio bism, but when I go thru the list of differently-defined objects, I'm not sure what "update" action means. 

What I *want* are the project bism objects to be updated with the definitions that are on the server. How can i do this/convince myself that's actually the direction the update is going? 

I don't want to lose my (deployed) work by "updating" the good server version with the obsolete VS project one!

thanks!

**Comment by sherifffruitfly** [comment]
Nevermind that's what source & target are for duh.
