### ISSUE TITLE
"TOM internal serialization error" with hybrid table

### ISSUE THREAD

**Issue by vagabond177** [microsoft/Analysis-Services#164]
Putting an incrementally refreshed table into hybrid mode (setting "Get the latest data in real time with Direct Query") causes ALM Toolkit operations on the dataset to fail with "TOM internal serialization error".

Tested with a new dataset using just one table with one column, imported from a SQL database. ALM Toolkit is comparing the local model with itself. Saved the test as a PBIT (attached).

 Incremental settings:

![image](https://user-images.githubusercontent.com/31447705/186423187-0d3e9885-ac29-40ed-97d1-e6489c70d62b.png)

ALM Toolkit options:
![image](https://user-images.githubusercontent.com/31447705/186423345-6f8d5e2e-e29d-4424-a863-9495f225caf1.png)

Running ALM Toolkit 5.0.32.

[OneTable.zip](https://github.com/microsoft/Analysis-Services/files/9416264/OneTable.zip)

**Comment by adsummer** [comment]
I have also encountered this error - please reach out if you need more examples

**Comment by christianwade** [comment]
Thanks for the heads up. Catching up from vacation. I have put investigating this on my todo list ...

**Comment by adsummer** [comment]
Hi Christian, Can you think of a workaround that might be better than below?

* I have Test and Prod environments
* I do all of my work in the Test Environment (without Hybrid tables)
* I push from dev to Prod, then in prod activate the hybrid tables
* Then go back to working in Test

Happy to chat with you during work hours, and thanks for all the work that you do.

**Comment by christianwade** [comment]
Hi all, sorry for the delay. This is a TOM serialization bug. It has been raised with the engineers and will require a new AMO release, and then a new ALM Toolkit build. I'll update when done.

**Comment by christianwade** [comment]
Hi all, latest release 5.0.33 should have this fixed. Please let me know if it worked for you.

**Comment by vagabond177** [comment]
Confirmed: it's resolved for me.

We did discover an entirely new issue where we get an TMSavePoint error when a calculated table uses a SUMMARIZE() or SUMMARIZECOLUMNS() function in the same model as a hybrid table, but that has nothing to do with ALM Toolkit. :)

Thanks for getting this fixed!
