### ISSUE TITLE
Power BI Desktop file is not detecting inside the ALM toolkit

### ISSUE THREAD

**Issue by mprofinder** [microsoft/Analysis-Services#165]
The power bi desktop drop down is not detected in the ALM toolkit, tried opening from External tools ribbon and also as application.

Installed version :
ALM toolkit = 5.0.32
Power BI Desktop =  2.108.825.0 64-bit (August 2022)

![image](https://user-images.githubusercontent.com/37399918/188667943-fee0a5ab-52e4-4984-a668-5e60fc5afee4.png)

**Comment by christianwade** [comment]
Hi, sorry for the delayed response. Is this still an issue? I haven't seen it before and it hasn't been reported by others, so it may be something environmental. Ideally, I'd get an repro on my dev environment to debug it.

**Comment by mprofinder** [comment]
Hi Christian
Thanks for your response, I was just validating this issue and found this is working fine now. I agree with you that it could be something temporary from the system.

**Comment by christianwade** [comment]
No worries. Let me know if reoccurs.
