### ISSUE TITLE
Monthly Partition Overlap

### ISSUE THREAD

**Issue by Guavaq** [Microsoft/Analysis-Services#17]
Hi there

When I am implementing this on the Monthly partition I am getting an overlap on the months, because currently it has it as shown below

![image](https://user-images.githubusercontent.com/31457981/40597723-7e81e0ba-6286-11e8-9d06-5bade49bc509.png)

Any idea how to get this resolved? As it stands I would need to manually make the change and have to reprocess the entire cube.

**Comment by Guavaq** [comment]
Hi Christian,

It uses a function which is in the picture of the first message. 

Is that what you are after? 

If you can see the image above it has the start of each month so there is an overlap on each monthly partition

**Comment by christianwade** [comment]
It needs to use a template function with placeholders for date range substitution. The template is stored in one of the database fields. Do you have the template query with the placeholders?

**Comment by Guavaq** [comment]
Here is the Template Query with the placeholders.

![image](https://user-images.githubusercontent.com/31457981/40686812-eb5f2976-63db-11e8-9f64-c22357ce62ae.png)

**Comment by christianwade** [comment]
OK that helps. As shown by the query, it just substitutes the {0} and {1} placeholders with the range values for each partition. These can be integer surrogate key, or datetime based (I can see you have IntegerDateKey=true). So you need to modify the template query so that, based on your dataset, will filter only on the required data for each partition

**Comment by Guavaq** [comment]
Thanks for that, please let me know if I am missing something, I thought that the placeholder {0} would be for the start of the month EG: 20180301 and the placeholder {1} would be for the end of the same month EG: 20180331

Is my assumption correct?

As currently it is putting them in as {0} - 20180301 and {1} - 20180401

Or how would I modify the Template Query for the end of the current month?

**Comment by christianwade** [comment]
That is correct yes. The data in each partition will be just what is returned by the query that is generated for each partition. I don't know the ins and outs of your dataset, what is returned by the GetFactData function, or which queries would work.

For testing you may want to run a simple query or 2 in Desktop with the M expressions copied and pasted from SSMS, check the data returned is what is expected

**Comment by Guavaq** [comment]
Ok thanks Christian, what I will do is change the Query to look for < {1} which will always be for the day before.

I just assumed that the {1} would always find the last day of the Month.

Thanks for getting back to me so quickly.

**Comment by christianwade** [comment]
You're welcome! The solution sounds reasonable. Glad you are unblocked.
