### ISSUE TITLE
COM error when trying to compare datasets online

### ISSUE THREAD

**Issue by alex-potter** [microsoft/Analysis-Services#176]
Tried with multiple workspaces and datasets. 

Confirmed still able to compare with local datasets

![image](https://user-images.githubusercontent.com/16261900/195725525-416f506a-6b82-4b14-9bf7-3a905f1da110.png)

**Comment by christianwade** [comment]
Sorry I missed this. If problem still persists and able to provide repro, please reopen and I'll work with you to repro.
