### ISSUE TITLE
BISM Normalizer for VS 2022

### ISSUE THREAD

**Issue by kr77025** [microsoft/Analysis-Services#177]
Can we have this wonderful tool work with Visual Studio 2022?

**Comment by christianwade** [comment]
Thank you for the feedback! It's on my to-do list. Just need to find time from my "day job" 😀

**Comment by ale3584** [comment]
I need this awesome tool for Visual Studio 2022 too!

**Comment by christianwade** [comment]
Sorry I didn't get to do this. Please try ALM Toolkit instead. You can set AS or SSDT as the source/target.
