### ISSUE TITLE
[Best-Practice-Rules] RLS should be checked on TablePermission objects

### ISSUE THREAD

**Issue by otykier** [microsoft/Analysis-Services#178]
It seems that [this rule uses a wrong scope](https://github.com/microsoft/Analysis-Services/blob/8e9a26c7988659389d336e881ebf1aa01e386f98/BestPracticeRules/BPARules.json#L222-L231). Either, change the BPA expression to use the `RowLevelSecurity` property of the tables, or change the scope to `TablePermission` instead of `Table, CalculatedTable`. Table objects do not have an `Expression` property, causing the rule to fail currently.

Recommend using the latter approach, as the BPA rule will then point to the exact table permission that uses dynamic security, instead of  pointing to a table (which could have many different table permissions assigned through different roles).

**Comment by m-kovalsky** [comment]
Thanks Daniel! I updated this to use TablePermission. This is fixed in v1.2.3 (just released).
