### ISSUE TITLE
Comparison Results not visible in UX, but export to Excel

### ISSUE THREAD

**Issue by AndrewFoulk1** [microsoft/Analysis-Services#179]
I think this is my first time running ALM Toolkit at my current job. So I am not 100% sure if this is definitely an ALM issue or potentially something to do with this PC and company settings, but it doesn't seem like it would be a computer setting.

When I run a comparison of 2 models (I tried multiple combinations of published vs local, published vs published, local vs local)
I do not see the results, visually in the ALM Toolkit application. It is a completely white screen underneath the Source and Target paths by the Menus at the top.

When I use the "Report Differences" to excel file, I can see the list of hundreds of objects that appear in the 1 file.

Is this a common issue?

**Comment by christianwade** [comment]
Hi, sorry for the delayed response. Is this still an issue? If yes, can you try installing the C++ Redist 2013 x86 and see if that fixes it?
https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by DataGuru311** [comment]
Hello Christian, my apologies for the delay as well. I finally got back around to this.
I have downloaded and installed the C++ Redist 2013 x86. Still not 100%
Even prior to this, recently I have had working examples where results of the compare has worked. Other times it did not.

The only precise example I can give at this time is what I just tested.
1 - I opened ALM Toolkit within the External Tools ribbon while working in Power BI Desktop, already using the local copy as the source, then chosing the target as a published online dataset.
*Results appeared on-screen as expected.

2 - I opened ALM Toolkit fresh from windows menu, choose both compare options. Once with both being published online datasets. Once with 1 published and 1 locally open.
*Both Results did NOT appear on-screen like I previously reported.

**Comment by christianwade** [comment]
Hi Andrew, can you share screenshot of the blank screen please? Hopefully that will give a clue.

Also please confirm when you go to Excel it's still showing items like you described in the 1st message. It's possible it's working now but there are no comparison items to show.

**Comment by AndrewFoulk1** [comment]
Hello Christian, I have been using ALM more lately and have not been experiencing the issue any longer. Either your more recent updates resolved, or something else on the local machine was the issue and has resolved as well.
Thank you for keeping in touch on this.
