### ISSUE TITLE
Support for Compatibility Level 1601

### ISSUE THREAD

**Issue by jashwood** [microsoft/Analysis-Services#187]
Could support please be added for Compatibility Level 1601 in ALM Toolkit
The maximum currently supported is reported as 1600

**Comment by christianwade** [comment]
Just did a release sorry for delay

**Comment by jashwood** [comment]
hmm still an issue - i'm not sure AMO supports 1601 yet?

**Comment by jashwood** [comment]
Did some digging... 
https://learn.microsoft.com/en-us/analysis-services/tabular-models/compatibility-level-for-tabular-models-in-analysis-services?view=asallproducts-allversions

**The latest supported compatibility level is 1600**

**Comment by christianwade** [comment]
Right it's not supported even though the latest TOM library contains it. We need to do this sometimes so other teams that take a dependency can use it.

I did another release today that I think works (although the additional metadata isn't supported by MS)

**Comment by jashwood** [comment]
Thanks! Can confirm this is working now on 1601, thank you for your prompt attention to this. 
It really helps me out!

**Comment by DKfromtheBay** [comment]
Hi Christian, I installed the latest version 5.0.44 but I'm getting the 1601 compatibility error. My Power BI desktop version is December 2023. Error message says "This combination of mixed compatibility levels is not supported. Source is 1601 and traget is 1601. Min Supported compatibility level is 1100 and max is 1600"

**Comment by christianwade** [comment]
Can you check the ALM Toolkit version in Help > Info? I just checked the code and tried with source and target both at 1601 couldn't repro

**Comment by DKfromtheBay** [comment]
> Can you check the ALM Toolkit version in Help > Info? I just checked the code and tried with source and target both at 1601 couldn't repro

My installed version is 5.0.33; our company portal has 5.0.44 but looks like that doesn't replace the old version I had already installed. I'll work with my helpdesk to update versions and confirm if the issue persists or not
