### ISSUE TITLE
BismNormalizer deployment with delegated permission and OAUTH token

### ISSUE THREAD

**Issue by Yavari** [microsoft/Analysis-Services#189]
We are trying to setup auto deployment in Azure devops but have encountered an issue I hope you can help me resolve.

I have first tried to use BismNormalizer with a system account and receive:

`Microsoft.AnalysisServices.Authentication.NonInteractiveLoginException: Unable to obtain authentication token using the credentials provided. If your Active Directory tenant administrator has configured Multi-Factor Authentication or if your account is a Microsoft Account, please remove the user name and password from the connection string, and then retry. You should then be prompted to enter your credentials.`

We have then switched to an App Registration that we use the refresh the PowerBI dataset and I receive:

```
--Comparing . . .
The following exception occurred:
Microsoft.AnalysisServices.ConnectionException: PowerBI Request Failed.

Action: Resolving the PBI workspace

Description:

Technical Details:
RootActivityId: fd4cecf7-****-****ac87-a88756ffa06a ---> System.Net.WebException: Fjärrservern returnerade ett fel: (401) Behörighet saknas.
```

What API/Permissions do I need to add to the App Registration to get it to work?
Do I need to add the *Application permission* Tenant.Read.All? That could be an issue for me since I don't think our Admins would allow it.
![image](https://user-images.githubusercontent.com/1221772/211295343-956b04e7-e8da-49eb-875b-d6268af6bc73.png)
We have solved the dataset refresh call by using an OAUTH token based on our system account and app registration. Where we have added *delegated permissions* Dataset.Read.All and Dataset.ReadWrite.All to the App Registration.
![image](https://user-images.githubusercontent.com/1221772/211295033-6077ac54-3d9f-40b7-9170-77e6d06d10e4.png)

We can add as many *deleted permissions* as needed. My questions is therefore. Can we use BismNormalizer with an OAUTH token and which *delegated permissions* do I need to add?

**Comment by christianwade** [comment]
Hi Yavari, 

I'm assuming your dataset is in Power BI Premium (not AAS). 

You should be able to use service principals. The permissions are the same as what you would need to execute TMSL scripts for metadata changes/refreshes from SSMS (this is all BISM Normalizer/ALM Toolkit is doing). Please see docs [here](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-connect-tools#service-principals) and [here](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-service-principal).

Once you get it working from SSMS, then you should be able to specify the SPN creds for unattended execution using the command line arguments listed on Page 32 of [this doc](https://github.com/microsoft/Analysis-Services/blob/master/BismNormalizer/Model%20Comparison%20and%20Merging%20for%20Analysis%20Services.pdf).

Hopefully that works for you.

Christian

**Comment by Yavari** [comment]
Thank you. Your link helped me. It though we were using the App Service APIs.
