### ISSUE TITLE
Astrace on SQL SSAS 2016 installation

### ISSUE THREAD

**Issue by rkaushik2007** [microsoft/Analysis-Services#19]
Hi,

I compiled the latest version of ASTrace from Codeplex and deployed it into SQL instance and when I started it It throws this error:

24/02/2018 01:02:18:  Cannot start Analysis Server trace: 

24/02/2018 01:02:18:  Analysis Server name: 'SSAS Server Name'

24/02/2018 01:02:18:  Trace definition : 'C:\ASTrace2016\Extended.tdf'

24/02/2018 01:02:18:  Error: Failed to initialize object as reader.

24/02/2018 01:02:18:  Stack Trace:    at Microsoft.SqlServer.Management.Trace.TraceServer.InitializeAsReader(ConnectionInfoBase serverConnInfo, String profileFileName)

   at ASTrace.Trace.ConnectOlap(TraceServer& traceServer, String SSASserver) in \\Path\ASTrace CS - 2016\ASTrace\Service1.cs:line 124

INNER EXCEPTION: Object reference not set to an instance of an object.

   at Microsoft.SqlServer.Management.Trace.TraceServer.InitializeAsReader(ConnectionInfoBase serverConnInfo, String profileFileName)
 
Any Clue!!

Regards
 Rajaniesh

**Comment by sqlsmithGit** [comment]
Hello,  I'm getting this same experience.  Anyone have any ideas?

**Comment by iamakashsingh** [comment]
Hello,

I am getting below error while installing ASTrace on SQL Server 2016.

Faulting application name: ASTrace.exe, version: 2.1.0.0, time stamp: 0x5b3ef2d1
Faulting module name: KERNELBASE.dll, version: 10.0.14393.2189, time stamp: 0x5abda7d6
Exception code: 0xe0434352
Fault offset: 0x000daa12
Faulting process id: 0x5034
Faulting application start time: 0x01d414f2034a5aff
Faulting application path: D:\ASTrace\ASTrace.exe
Faulting module path: C:\windows\System32\KERNELBASE.dll
Report Id: bb4c041a-deea-4a1f-8214-9c0c22a9196f
Faulting package full name: 
Faulting package-relative application ID: 

Application: ASTrace.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at ASTrace.Trace..ctor()
   at ASTrace.Program.Main()

Regards,
Akash

**Comment by narayan-dhamu** [comment]
HI,
I got this error.. Any solution for this?

Cannot start Analysis Server trace: 
Analysis Server name: 'xxx'

 Trace definition : '---\Capture2.tdf'
 Error: Failed to initialize object as reader.

Stack Trace:    at Microsoft.SqlServer.Management.Trace.TraceServer.InitializeAsReader(ConnectionInfoBase serverConnInfo, String profileFileName)
   at ASTrace.Trace.ConnectOlap(TraceServer& traceServer, String SSASserver) in ...\Service1.cs:line 124
INNER EXCEPTION: Object reference not set to an instance of an object.
   at Microsoft.SqlServer.Management.Trace.TraceServer.InitializeAsReader(ConnectionInfoBase serverConnInfo, String profileFileName)

**Comment by rajaniesh** [comment]
No idea as Microsoft is not replying and helping on this.

**Comment by landrymd** [comment]
Here's how I got ASTrace 2016 to work. 

First, install SSMS 2017 on the server you want to run ASTrace. This installs the 14.100.0.0 version DLLs. Note, the 14.0.0.0 DLLs produce the errors described above.

Second, build the "ASTrace 2016" solution using Visual Studio. (I used 2012.)
This machine also must have SSMS 2017 installed if different from above.
Application->Target framework->.NET Framework 4
Build->Platform Target->x86 (ASTrace must be a 32-bit executable.)
Add references to Microsoft.SqlServer.ConnectionInfo and Microsoft.SqlServer.ConnectionInfoExtended from C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio

Third, use this as your ASTrace.exe.config template:
<?xml version="1.0"?>
<configuration>
    <configSections>
        <sectionGroup name="applicationSettings" type="System.Configuration.ApplicationSettingsGroup, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
            <section name="ASTrace.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false"/>
        </sectionGroup>
    </configSections>
    <applicationSettings>
        <ASTrace.Properties.Settings>
            <setting name="AnalysisServerNames" serializeAs="String">
                <value>localhost,localhost\tabular</value>
            </setting>
            <setting name="SQLServer" serializeAs="String">
                <value>localhost\SQLInstance</value>
            </setting>
            <setting name="SQLServerDatabase" serializeAs="String">
                <value>TraceDB</value>
            </setting>
            <setting name="TraceTableName" serializeAs="String">
                <value>ASTraceTable</value>
            </setting>
            <setting name="TraceDefinition" serializeAs="String">
                <value>Standard.tdf</value>
            </setting>
            <setting name="PreserveHistory" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="RestartRetries" serializeAs="String">
                <value>3</value>
            </setting>
            <setting name="RestartDelayMinutes" serializeAs="String">
                <value>5</value>
            </setting>
        </ASTrace.Properties.Settings>
    </applicationSettings>
  <runtime>
    <assemblyBinding
       xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.SqlServer.SqlClrProvider" publicKeyToken="89845dcd8080cc91"/>
        <bindingRedirect oldVersion="14.0.0.0" newVersion="14.100.0.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.SqlServer.ConnectionInfo" publicKeyToken="89845dcd8080cc91"/>
        <bindingRedirect oldVersion="14.0.0.0" newVersion="14.100.0.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.SqlServer.ConnectionInfoExtended" publicKeyToken="89845dcd8080cc91"/>
        <bindingRedirect oldVersion="14.0.0.0" newVersion="14.100.0.0"/>
      </dependentAssembly>
     </assemblyBinding>
  </runtime>
</configuration>

**Comment by landrymd** [comment]
Third, use this as your ASTrace.exe.config template:

`<?xml version="1.0"?>
<configuration>
    <configSections>
        <sectionGroup name="applicationSettings" type="System.Configuration.ApplicationSettingsGroup, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
            <section name="ASTrace.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false"/>
        </sectionGroup>
    </configSections>
    <applicationSettings>
        <ASTrace.Properties.Settings>
            <setting name="AnalysisServerNames" serializeAs="String">
                <value>localhost,localhost\tabular</value>
            </setting>
            <setting name="SQLServer" serializeAs="String">
                <value>localhost\SQLInstance</value>
            </setting>
            <setting name="SQLServerDatabase" serializeAs="String">
                <value>TraceDB</value>
            </setting>
            <setting name="TraceTableName" serializeAs="String">
                <value>ASTraceTable</value>
            </setting>
            <setting name="TraceDefinition" serializeAs="String">
                <value>Standard.tdf</value>
            </setting>
            <setting name="PreserveHistory" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="RestartRetries" serializeAs="String">
                <value>3</value>
            </setting>
            <setting name="RestartDelayMinutes" serializeAs="String">
                <value>5</value>
            </setting>
        </ASTrace.Properties.Settings>
    </applicationSettings>
  <runtime>
    <assemblyBinding
       xmlns="urn:schemas-microsoft-com:asm.v1">
      <probing privatePath="ManagementStudio"/>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.SqlServer.SqlClrProvider" publicKeyToken="89845dcd8080cc91"/>
        <bindingRedirect oldVersion="14.0.0.0" newVersion="14.100.0.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.SqlServer.ConnectionInfo" publicKeyToken="89845dcd8080cc91"/>
        <bindingRedirect oldVersion="14.0.0.0" newVersion="14.100.0.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.SqlServer.ConnectionInfoExtended" publicKeyToken="89845dcd8080cc91"/>
        <bindingRedirect oldVersion="14.0.0.0" newVersion="14.100.0.0"/>
      </dependentAssembly>
     </assemblyBinding>
  </runtime>
</configuration>
`

**Comment by landrymd** [comment]
Other notes...

Error: "Microsoft.SqlServer.Management.Trace.TraceServer.InitializeAsReader" "Object reference not set to an instance of an object." 

The TraceServer class only works from 32-bit clients.  This is because the underlying mixed-mode C++/ATL PFCLNT.DLL is supplied only in a 32-bit version.

**Comment by SQLPRODDBA** [comment]
> Other notes...
> 
> Error: "Microsoft.SqlServer.Management.Trace.TraceServer.InitializeAsReader" "Object reference not set to an instance of an object."
> 
> The TraceServer class only works from 32-bit clients. This is because the underlying mixed-mode C++/ATL PFCLNT.DLL is supplied only in a 32-bit version.

Does this mean AsTrace won't work on 64 bit systems? If not, how to fix this error?

**Comment by landrymd** [comment]
Yes it runs on 64-bit systems but as a 32-bit app. 

https://docs.microsoft.com/en-us/windows/win32/winprog64/running-32-bit-applications

**Comment by SQLPRODDBA** [comment]
> Yes it runs on 64-bit systems but as a 32-bit app.
> 
> https://docs.microsoft.com/en-us/windows/win32/winprog64/running-32-bit-applications

Thanks! I am getting the same object reference not set error. Would you please help me fix it? Also it would be great if you can direct me on a link or blog post that shows step by step process to install it on x64 boxes with SSAS 2017. Want to make sure I did the installation correctly.

**Comment by landrymd** [comment]
Did you try building it with Visual Studio as I described above?
