### ISSUE TITLE
Wrong proposal for 1-(x/y) rule

### ISSUE THREAD

**Issue by MarioMue13** [microsoft/Analysis-Services#192]
Hi I just tried to get rid of this warning and found out that there is an error in the recommendation:
![image](https://user-images.githubusercontent.com/74975641/212827029-43ec508b-ce77-42b3-9b7f-b7c593d47693.png)
[BPARule-Issue.xlsx](https://github.com/microsoft/Analysis-Services/files/10432046/BPARule-Issue.xlsx)

**Comment by m-kovalsky** [comment]
This has been updated in [1.2.5](https://github.com/microsoft/Analysis-Services/tree/master/BestPracticeRules)
