### ISSUE TITLE
AADSTS900023: Specified tenant identifier 'authorize' is neither a valid DNS name, nor a valid external domain.

### ISSUE THREAD

**Issue by fassetar-work** [microsoft/Analysis-Services#194]
https://github.com/microsoft/Analysis-Services/blob/2e3df0061de5c5c181ac0fcfe0f344779cc893a5/RestApiSample/RestApiSample/Program.cs#L70

Error:
Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: 'AADSTS900023: Specified tenant identifier 'authorize' is neither a valid DNS name, nor a valid external domain.

I get this error when I place my tenant id.

**Comment by andrew-collset** [comment]
I am experiencing the same error.
Could anyone advise?

**Comment by andrew-collset** [comment]
> ?

I took 
oauth2/authorize"; 

off the end of the URL and it worked.

**Comment by christianwade** [comment]
Sorry I missed this. If problem still persists, please open a CSS ticket as this is core AS functionality.
