### ISSUE TITLE
Can't run latest version of BismNormalizer

### ISSUE THREAD

**Issue by Yavari** [microsoft/Analysis-Services#196]
I get following exception when I tried to run latest version of BismNormalizer included with ALM Toolkit 5.0.33 downloaded from https://github.com/microsoft/Analysis-Services/releases/

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'BismNormalizer, Version=5.0.32.0, Culture=neutral, PublicKeyToken=aa6675aad991a644' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at BismNormalizer.CommandLine.Program.Main(String[] args)
```

We need version 5.0.33 to resolve https://github.com/microsoft/Analysis-Services/issues/167

**Comment by Yavari** [comment]
Is this only an issue for me? It seems to be an distribution issue that BismNormalizer 5.0.32 is packaged with ALM Toolkit 5.0.33

**Comment by christianwade** [comment]
Hi Yavari, sorry for the delayed response. Are you running from the command line?

**Comment by Yavari** [comment]
Yes, I am calling BismNormalizer.exe from command line with parameters.
My problem is that the wrong version of BismNormalizer is distributed with the installation file at https://github.com/microsoft/Analysis-Services/releases/ and it can't even run since the dlls are for 5.0.33. You can see a screenshot of the version information bellow:
![image](https://user-images.githubusercontent.com/1221772/217175014-0411532a-a99c-47d8-a505-834e90178e2d.png)

**Comment by Yavari** [comment]
I ended up building BismNormalizer.exe from source in order to proceed. Should I close the issue or do you want me to keep it open until the distribution is resolved?

**Comment by christianwade** [comment]
Hi, I've added a note to check this during the next build/release. I'm glad you're unblocked. Can close for now. Thank you.

**Comment by christianwade** [comment]
Hi, I did a release and tested it's now showing the same version of BismNormalizer.exe
