### ISSUE TITLE
BPARule: Remove data sources not referenced by any partitions

### ISSUE THREAD

**Issue by justBlindbaek** [microsoft/Analysis-Services#197]
I'm using a subset of the "official" BPA rules as part of a build pipeline in Azure DevOps. I creates a new Structured Data Source (Power Query) to use on a fact table, so I could setup the IR policy. The rest of the tables/partitions in the model uses another Provider Data Source (Legacy).

Now I'm getting a violation on the "[Maintenance] Remove data sources not referenced by any partitions" rule. The expression for the rule is: 

`UsedByPartitions.Count() == 0`

I thought there might be a bug in the `UsedByPartitions` class as it apparently don't take into account that partitions generated by an Incremental Refresh Policy don't have a direct reference to a Data Source. The reference is part of the `sourceExpression` on the table level.

Daniel Otykier quickly [responded to my issue](https://github.com/TabularEditor/TabularEditor/issues/1076) with a suggestion to extend the the rule to  also check `sourceExpression` and the query on M partitions in general: 

```
UsedByPartitions.Count() == 0 
and not Model.Tables.Any(SourceExpression.Contains(OuterIt.Name))
and not Model.AllPartitions.Any(Query.Contains(OuterIt.Name))
```

The scope of the rule is both `ProviderDataSource` and `StructuredDataSource` so another option is to split it into two, so the rule can be more specific.

**Comment by m-kovalsky** [comment]
Good catch, Just. I will update the logic of this rule accordingly in the next version of the BPA rules. Thanks @otykier!

**Comment by m-kovalsky** [comment]
This has been updated in [1.2.5](https://github.com/microsoft/Analysis-Services/tree/master/BestPracticeRules)
