### ISSUE TITLE
ALM Toolkit Usage with external Tenants (5.0.33)

### ISSUE THREAD

**Issue by jonaskoeASYS** [microsoft/Analysis-Services#199]
Hello,

often I work with datasets, that are not part of my home tenant. Therefore I need to sign in as an external guest user. In prior versions (i.e. 5.0.32) I could use the method described in https://youtu.be/x1xMxRXQ2So?t=114: In the Microsoft Sign in window, I use Sign-in options -> Sign in to an organization to sign in with the target tenant. 

With 5.0.33 I am only asked once to login. I can sign-in for the source and choose the dataset, but for the target no sign-in popup appears and therefore the dataset dropdown is empty:
![image](https://user-images.githubusercontent.com/79694944/219439651-2d924093-acd3-4dde-8464-13ec43c8514e.png). Before this version I was prompted two times, for the source and the target, but then each dataset-dropdown field was filled with the corresponding dataset names. 

Even if i want to compare the deployed dataset from the foreign tenant with a file (.bim), I am getting an error indication that there is an issue with the AAD token: 
![image](https://user-images.githubusercontent.com/79694944/219437693-e9f31ec8-b5b6-48ea-9b51-ac6ecb9b197d.png).

**Comment by christianwade** [comment]
Hi Jonas. Thanks for raising. We'd like to investigate this internally. Can you switch this conversation to e-mail? My address starts with chwade ...
