### ISSUE TITLE
Extend to provide Process Add frequency withing a partition

### ISSUE THREAD

**Issue by shaunryan** [microsoft/Analysis-Services#2]
I'd like it to support process add and mixed partitioning... e.g. have a Month partitions but in the latest month have a process add frequency so I can process add days until the next month turns over. Am happy to extend... how can I contribute?

**Comment by christianwade** [comment]
Hi, sorry for the late reply. The current version allows calling the merge function, and essentially can configure multiple configs for each granularity. There is out of the box functionality like this coming for PBI Premium soon too
