### ISSUE TITLE
AsPartitionProcessing does not work correctly with SSAS 2022.

### ISSUE THREAD

**Issue by ale3584** [microsoft/Analysis-Services#206]
Tool not showing Memory Usage of Databases just Memory Usage of Users connections.

**Comment by ale3584** [comment]
Fixed?

**Comment by christianwade** [comment]
Sorry I missed this previously. Can you elaborate on what you are expecting? Are you referring to the AsPerfMon sample? Whilst not 100% accurate, it shows memory usage by database. I'm not sure where to tool provides memory usage of users connections that you're referring to.
