### ISSUE TITLE
ALM Toolkit doesn't report a difference when the M code in partition changes

### ISSUE THREAD

**Issue by edhans** [microsoft/Analysis-Services#209]
After doing comparison of different datasets, ALM Tookit doesn't report a difference in a table if the M code in the Partition of the table has changed but nothing else about the object. So the table results and schema are identical, but the M code changed (different source).

Version 5.0.41.

**Comment by christianwade** [comment]
Hi Ed, can you check the options settings please? The below screenshot shows the settings that affect comparison and update behavior.

![image](https://user-images.githubusercontent.com/20731873/227670892-3e121fbb-058f-4806-882c-6c31bc5b8713.png)

**Comment by edhans** [comment]
That was it. Mine was set to this. I don't think I've ever changed the options before. Thanks.

![image](https://user-images.githubusercontent.com/45298358/227687583-5bc27155-5cf9-4da8-9716-94c9dde45da3.png)

**Comment by christianwade** [comment]
Glad you're unblocked!
