### ISSUE TITLE
Mixed Granularity Question

### ISSUE THREAD

**Issue by RJVerm** [microsoft/Analysis-Services#21]
I have some difficulty grasping the Rolling Window setup in combination with a Mixed Granularity.

What i want:
- Data from years previous to 2018 (<= 2017) in a Yearly granularity
- Data from the months prior to the current month (< currentmonth) in a Monthly granularity
- Data from the current month in a daily granularity

I want only the last 7 days to be incrementally processed daily. All other partitions will be refreshed weekly.

My current setup is like this:
**Model**
![image](https://user-images.githubusercontent.com/42602548/44450126-692b9c80-a5f0-11e8-834e-ddfa9637e548.png)
**PartitionConfiguration**
![image](https://user-images.githubusercontent.com/42602548/44450193-95471d80-a5f0-11e8-820c-aeb4f83c4448.png)

This setup returns an error because the dates overlap, which is 'correct'. This is due to the fact that the number of partitions isn't dynamically calculated.
I tried another setup with limiting the number of fullpartitions (21), which gave me the right configuration yesterday (2018-08-21), but today (2018-08-22) when i ran the script again this morning the partition of the first day of this month (20180801) was removed because it fell out of scope. (it was 'the 22nd partition')

Am I trying to do something that isn't supported out of the box, should I try another approach with the configuration or look at it in a completly diffrent way?

I expected the partition for the first day of the month to remain and a new partition for this day to be created.

Could you help me understand more about the configuration and tell me if it's possible to achive what I want. Thank you in advance.

**Comment by eddingtonm** [comment]
Hi @RJVerm ,

I'm also quite stuck with the same issue. I don't think this feature is out of the box with the TOM.

I'm having to increase memory on my Azure AS in order to process + then have to firstly delete partitions in order to roll them up into a month without any overlap.

Did you perhaps manage to fix this issue?
