### ISSUE TITLE
Mixed Compatibility Mode Is not Supported.

### ISSUE THREAD

**Issue by TreCook** [microsoft/Analysis-Services#213]
I am not sure what caused this but I recently enabled the Power BI preview feature for dynamic format string (link below).

https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-dynamic-format-strings

![image](https://user-images.githubusercontent.com/73838315/234741651-7a274f85-aa7f-417f-8cf0-917e27b104c0.png)

**Comment by christianwade** [comment]
Sorry I missed this one. I believe this is fixed now.

**Comment by TreCook** [comment]
You rock.
