### ISSUE TITLE
PowerBI_V1 not supported: using Apr 2023 PBI desktop release

### ISSUE THREAD

**Issue by DerekJarvis** [microsoft/Analysis-Services#214]
Similar to this issue https://github.com/microsoft/Analysis-Services/issues/75 I get the `PowerBI_V1 not supported` error when trying to sync between a remote datasource and a local PBIX file. I'm using the latest version of PowerBI Desktop with all preview features enabled, but this still happens.

I found out that the issue was I was using an empty file. Once I updated the target PBIX file with at least one data source (an Excel file) it started showing me the changes perfectly.

Perhaps the error message can be improved or this situation can be handled automatically?

**Comment by christianwade** [comment]
Thanks for the feedback Derek. Will add it to the list of items to look into.
