### ISSUE TITLE
ALM Toolkit compatibility level error using latest Desktop ver. 

### ISSUE THREAD

**Issue by paulturley** [microsoft/Analysis-Services#216]
ALM toolkit complains when connecting to two copies of the same dataset, both authored in the latest version of Desktop, when comparing the XMLA endpoint and local Desktop instance.
 
The database compatibility level of 1567 is below the minimal compatibility level of -2…
 
Checking the models, they are both at 1567.

 
 
![ALMToolkitError](https://github.com/microsoft/Analysis-Services/assets/7576125/79f4eb35-6a74-43a4-8dc0-5a702dfc5dac)

**Comment by christianwade** [comment]
Hi Paul, I'm assuming the XMLA endpoint version is in PBIP, right? If it were in AAS, you could get this error since parameters not supported.

Are you using the latest version of ALM Toolkit? There was a recent fix associated with CompatibilityMode that might address this this.
