### ISSUE TITLE
User does not have permission to call the Discover method.

### ISSUE THREAD

**Issue by bbragaferreira** [microsoft/Analysis-Services#219]
Using versions 5.0.41 and 5.0.33. earlier releases. 

When trying to connect to the dataset to compare it against a Power BI Source. I get the error message "The user does not have permission to call the Discover method." after entering my credentials. 

The model in the power bi service has a configured gateway connecting to the data source.

**Comment by christianwade** [comment]
Hi, I wish I could provide more specific help, but all I can suggest is this is probably an issue that is orthogonal to ALM Toolkit.

Can you script out the changes (button on ALM Toolkit ribbon) and apply the script from SSMS? If you get the same error there, it is an orthogonal issue (which I don't know right now if is a Power BI bug or not).

ALM Toolkit under the covers just generates the TMSL script and bubbles up the error message.
