### ISSUE TITLE
ALM Toolkit isn't recognizing my open desktop client files

### ISSUE THREAD

**Issue by jenmSkyPoint** [microsoft/Analysis-Services#220]
I'm using ALM Toolkit 5.0.41 and Desktop client Version: 2.117.984.0 64-bit (May 2023).

Steps:

Launch ALM Toolkit (from External tools) and 
Open the Connections dialog, 
Select Power BI Desktop as the source.

What I see: the dropdown is blank. I have two desktop client files open.

**Comment by christianwade** [comment]
Hi, I'd like to fix this for you, but I'm struggling to repro it. I just tried it and it is listing my open Desktop files. Do both the Desktop file instances have datasets within them, or are they live connect reports?

**Comment by jenmSkyPoint** [comment]
Hmmm. None of the reports were live connect files.

The two files I was trying to compare were both quite large, over 800,000 KB.

I then tried a handful of other reports of varying sizes. One was recognized (81,000 KB), but then a bunch of similarly sized files were not recognized. So, size may or may not be a factor 😊.

I’ve moved on for now, so I guess let it rest.
I was able to compare my files by unzipping template files and diffing the text.

I’ve appreciated using your tool in the past (and all you do for the community), so this is unfortunate! Sigh.

- Jen

**Comment by andreas-developer** [comment]
Same thing happened to me today after updating PBI Desktop to the June edition, after investigating for a while I decided to start going back in versions and it works again if I install the April release but nothing later than that.

Was running an older version of ALM Toolkit first (sorry, didn't write down which version) and updated to 5.0.43 but it didn't work until I installed the April release of PBI desktop.

**Comment by christianwade** [comment]
I believe it's been fixed now in https://github.com/microsoft/Analysis-Services/releases/tag/5.0.44  Please confirm.

**Comment by jenmSkyPoint** [comment]
Hmmm. Blocked so far (probably) by my corporate IT security team... Can't run the installer.
I've sent an inquiry to my IT department...

I would expect that I could click on something to enable a "Run" button but clicking on the (not visible here) More info link just resolves to the screen below.

I'm not sure if there's some sort of identifier that you can include in what you've done to make Windows Defender happier, or if my IT department needs to enable something.

Stay tuned.

***@***.***

- Jen

**Comment by christianwade** [comment]
On backlog to create a digital cert to help with this when get the bandwidth. In the meantime, should be able to explicitly choose to install it but it's possible it's blocked by Windows policy settings
