### ISSUE TITLE
Error Upon Refreshing Large Yearly Partition from TE3

### ISSUE THREAD

**Issue by JeridInsight** [microsoft/Analysis-Services#222]
I am trying to refresh a large yearly partition against Snowflake, and every time I attempt it (after 3 hours of loading) it fails with this error.  I have this same exact model in another workspace and it refreshed just fine.  The error says:

"An unexpected error occured (file 'TMSavePointValidation.cpp', line 422, function 'TMSavedPoint::VerifyProxyCreationAllowed')" 

![image](https://github.com/microsoft/Analysis-Services/assets/105085417/710e502b-6175-485b-9e3c-dd4b86b21b4f)

**Comment by christianwade** [comment]
Hi, that may be an AS engine bug. To get it routed to the engineers to debug it, need a CSS ticket filed

**Comment by JeridInsight** [comment]
No.  What is the process / link?  I will fill one out.

**Comment by christianwade** [comment]
Great. Should be to open a support case at https://powerbi.microsoft.com/en-us/support/

**Comment by JeridInsight** [comment]
https://admin.powerplatform.microsoft.com/ticket/2306230040008572
