### ISSUE TITLE
Connection to Azure Analysis service fails if multi-factor is enabled on account

### ISSUE THREAD

**Issue by sgojgini85** [microsoft/Analysis-Services#23]
I have created Azure Analysis Service instance with access to given to account from Azure Active Directory. I can connect successfully using a machine on domain with either "Active Directory - with Password" or "Active Directory - Universal with MFA Support". However if set the configuration to integrated auth I would get error below. 

`
Exception occurred: 08:21:47 PM
Exception message: Exception has been thrown by the target of an invocation.
Inner exception message: password_required_for_managed_user: Password is required for managed user
`

and when disable Integrated Auth and provide username and password through command prompt then I would get this error. 
`
Exception occurred: 07:55:40 PM
Exception message: Exception has been thrown by the target of an invocation.
Inner exception message: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '4ac7d521-0382-477b-b0f8-7e1d95f85ca2'.
Trace ID: 7a724497-67e9-492f-b60c-0a5945c63000
Correlation ID: 639928ef-c8d8-4a63-8ce0-15e8b26e65af
Timestamp: 2018-09-21 19:55:40Z
`
Is it possible to provide support for multi-factor account or should we setup account without one.

**Comment by kkho** [comment]
Any updates on this? I have the same issue as @sgojgini85 .

**Comment by Geraldziu** [comment]
This is related to what tool? If it's about AsPartitionProcessing have you tried to move from account authentication to service principal? I did that and for starter i don't have to remember to change password every 90 days :)

**Comment by LaguideHalid** [comment]
Hello, 
I have the same issue.
I want to use the AsPartitionProcessing solution with a Azure table.
But I have the same issue than  @sgojgini85 and @kkho 
Did you find the solution to connect on Azure Database ?
Is AsPartitionProcessing working on Azure architecture ? 

Thank you for your help.

**Comment by christianwade** [comment]
Have you tried using a service principal?
https://docs.microsoft.com/en-us/azure/analysis-services/analysis-services-service-principal

Also make sure you build AsPartitionProcessing with the latest client libs
https://www.nuget.org/packages/Microsoft.AnalysisServices.retail.amd64/
