### ISSUE TITLE
Order Rules?

### ISSUE THREAD

**Issue by PaulAGDoherty** [microsoft/Analysis-Services#230]
Is it possible to order the rules. I couldn't find an option, but I reordered to JSON which seemed to work on my machine. But someone else then working with the same JSON seems to see them in a different order. Or alternatively how to I share the rules I have made ineffective. Thanks

**Comment by m-kovalsky** [comment]
The order the BPA rules show up in the Best Practice Analyzer is the order in which they appear in the BPARules.json file.
