### ISSUE TITLE
Bounce email for pbibestpractice@microsoft.com

### ISSUE THREAD

**Issue by aols0228** [microsoft/Analysis-Services#233]
Hi, I got a "Could not be delivered email" after I tried to send an email to pbibestpractice@microsoft.com
Should it be operational?

<[pbibestpractice@microsoft.com](mailto:pbibestpractice@microsoft.com)>: host
    microsoft-com.mail.protection.outlook.com[104.47.53.36] said: 550 5.4.1
    Recipient address rejected: Access denied. AS(201806281)
    [BL2NAM06FT009.Eop-nam06.prod.protection.outlook.com
    2023-10-16T14:11:51.157Z 08DBCDB2DB5076DF] (in reply to RCPT TO command)

**Comment by m-kovalsky** [comment]
Please try again. This has ben resolved.
