### ISSUE TITLE
ALM Toolkit not showing results of comparison

### ISSUE THREAD

**Issue by MOgbechie** [microsoft/Analysis-Services#235]
ALM Toolkit version 5.0.44 is not able to show the results of comparison between Power BI Desktop and Dataset in the service. It gives the message "ALM Toolkit - finished comparing datasets" but displays no visual way of confirming this. Can this be looked into please?

**Comment by christianwade** [comment]
Hi, thanks for raising! I would need to create repro to debug it. Can you check the Options settings? It's possible that based on the settings, it's not picking up any diffs so it's showing a blank differences grid by design.

**Comment by MOgbechie** [comment]
Hi Christian, thanks for getting back to me. I've just tried this again and just like magic, the visual comparisons are back up and running. Not sure how or why!

**Comment by christianwade** [comment]
No worries. Glad you're unblocked!

**Comment by christianwade** [comment]
No worries. Glad you're unblocked!
