### ISSUE TITLE
Browser auth compatibility issues

### ISSUE THREAD

**Issue by pablogonzalez3** [microsoft/Analysis-Services#239]
When connecting to premium environment there is browser compatibility issue making unable to connect to the account.  The company has an authentication that gets us to the company portal single sign on auth.  

Please adjust your browser setting:
In Internet Explorer 8 please go to menu Tools > Compatibility View Settings and uncheck all options.
Then reload this page (e.g. pressing "F5" key).

**Comment by christianwade** [comment]
Sorry for delayed response. I'm not sure if this is ALM Toolkit or BISM Normalizer related, but let us know if needed
