### ISSUE TITLE
The type or namespace name 'MPartitionSource' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by renanalmeidjr** [microsoft/Analysis-Services#24]
Hi

I'm trying to get rid of this error with no success. I already tried a new VM installing VS 2017, SSDT 2017 from zero but no success.

I also tried installing the AMO from SQL Server 2016 Feature Pack in another machine (Since i can't install it on a machine with SSDT 2017) and copying the Microsoft.AnalysisServices.DLL installed on the C:\Program Files (x86)\Microsoft SQL Server\130\SDK path but no success also.

Could you please give me some guidance on how to get this namespace working properly on my project?

Thank you very much.
Renan Ribeiro

**Comment by renanalmeidjr** [comment]
Hi Guys,
Got it working with the following nuget package: 
Install-Package Microsoft.AnalysisServices.retail.amd64 -Version 15.7.0.2 

Maybe would be good to mention on the documentation.

THanks a lot!
\o/

**Comment by fatemehd85-sa** [comment]
HI,
