### ISSUE TITLE
ALM toolkit cannot connect to server

### ISSUE THREAD

**Issue by Lindstrome** [microsoft/Analysis-Services#240]
First of all, thank you for a fantastic product! However, I am encountering an issue

When connecting ALM toolkit to remote workspaces I get an error that says Cannot connect to server. 

I have an old computer with an installation of ALM toolkit, it works fine connecting to the same workspaces through that computer.

What I have tried: 

1. Reinstalling ALM toolkit
2. Installing the same version of ALM toolkit as on my old computer (5.0.33) this makes no difference compared to the latest version
3. Connecting to the same workspaces through tabular editor, which works fine
4. Trying to connect to workspaces on anther clients tenant with a different account
5. Connecting to local bim files (works fine) 
6. Let ALM toolkit though the firewall
7. Turning off my firewall
8. Turning off windows defender

Any suggestions on what might be going on here?

**Comment by christianwade** [comment]
Hi, thanks for the feedback. Can you connect from SSMS from that machine? Sounds like an XMLA connectivity issue.

**Comment by Lindstrome** [comment]
Hi Christian, thanks for replying so quickly. 

Connecting to the workspaces through the XMLA endpoint work fine using both SSMS and Tabular Editor 3, I can edit settings, deploy to different workspaces and refresh individual tables through those tools. I tried scripting individual tables in an Adventureworks model I have in a workspace. Here are the first part of the results: 
<img width="236" alt="image" src="https://github.com/microsoft/Analysis-Services/assets/84722853/d9549085-d600-4c9f-b26d-4751d214c925">

**Comment by Lindstrome** [comment]
Hello again, if anyone has a similar problem, I had to manually enter which semantic model to compare with in each workspace. After doing that I get a drop down list of each data model in the workspace.
