### ISSUE TITLE
fabricps-pbip exporting Reports with special charaters

### ISSUE THREAD

**Issue by JoCalheiros** [microsoft/Analysis-Services#246]
Using the Export-FabricItems function in the fabricps-pbip module, i'm getting an error while exporting items with special characters as displayName.

Set-Content: A parameter cannot be found that matches parameter name 'AsByteStream'.

Out-File: Cannot perform operation because the wildcard path C:\Users\...\item.metadata.json did  
not resolve to a file.

![image](https://github.com/microsoft/Analysis-Services/assets/158462404/99ded5cc-ea94-44a6-9112-43f3b14673b6)

I've added this -replace in FabricPS-PBIP.psm1 and it works fine
modules\FabricPS-PBIP.psm1

![image](https://github.com/microsoft/Analysis-Services/assets/158462404/aca3065a-eba1-4027-afe2-1fbc29c3cdd1)

Is this a correct approach?

Thanks

**Comment by RuiRomano** [comment]
Thanks. Fixed 942285ec9dbfb66a1a58f559ae8e364c7ec56b55
