### ISSUE TITLE
Remove-FabricItems fails without setting dummy value for $fabricHeaders

### ISSUE THREAD

**Issue by will-byrne-cardano** [microsoft/Analysis-Services#249]
[This line](https://github.com/microsoft/Analysis-Services/blob/cff9923a8496d9ecfbccfd69d2270baa641c7a35/pbidevmode/fabricps-pbip/FabricPS-PBIP.psm1#L831C5-L833C6) checks for the existence of the variable `$fabricHeaders` and if it doesn't exist it tries to call a function `Get-FabricHeaders` which doesn't exist. 

I think this check can be removed as `$fabricHeaders` is set in the function `InvokeFabricAPIRequest`. 

Happy to put in a PR. Is the function there as a placeholder for something that will exist? Current workaround is to just do:
```pwsh
$fabricHeaders = @{}
```
before calling this function.

**Comment by RuiRomano** [comment]
Thanks. Fixed 942285ec9dbfb66a1a58f559ae8e364c7ec56b55
