### ISSUE TITLE
ALM Toolkit won't ignore polling expression

### ISSUE THREAD

**Issue by bobvizion** [microsoft/Analysis-Services#250]
When comparing models using ALM Toolkit, I have the option to ignore partitions, but no option to ignore Polling Expressions. The existence of the Polling Expression in the target is showing as a change, which means we would wipe it out if the source table actually does have a necessary change.

**Comment by christianwade** [comment]
Hi bobvizion, thanks for the feedback. Yes, there is no "ignore polling expression" or "ignore refresh policy". I agree these would be helpful, but just haven't got to doing them.

In the meantime, you should be able to wiping out the polling expression when the source table has a necessary change by selecting the following option to retain refresh policy. Can you try it?

![image](https://github.com/microsoft/Analysis-Services/assets/20731873/cce47b2d-e9b6-4a24-b4c1-7ca69a24c05e)

**Comment by bobvizion** [comment]
Hi Chrisian,

What an honor to get a reply from a master! Thanks for all of the help over my 15-year career thus far!

I saw the Polling Expression show up as a change in ALM Toolkit and incorrectly assumed that any desired changes from the source table would automatically include the wiping out of the setting on the destination table on an Update. Thankfully, this is not the case if ‘Retain Refresh Policy’ is chosen. Thanks for clearing that up.

Keep up  the good work,

Bob


Bob Lehmann Sr. Analytics Developer
(440) 799-2524 (Cell)
(216) 393-5933 (Main) |(252) 354-3647 (Fax)
4500 Rockside Rd. Suite 120
Independence OH 44131
United States


[cid:microsoftteams-image(2)_027ea196-40ce-452c-9850-6dca316f6a7e.png]<http://transimpact.com/>   [https://transimpact.com/wp-content/uploads/2021/07/TI-INC-5000-sig.png]  [https://transimpact.com/wp-content/uploads/2021/07/TI-Facebook-sig-blue.png] <http://facebook.com/TeamTransImpact>  [https://transimpact.com/wp-content/uploads/2021/07/TI-twitter-sig-blue.png] <https://twitter.com/TeamTransImpact>  [http://transimpact.com/wp-content/uploads/2021/07/TI-youtube-sig-blue.png] <https://www.youtube.com/channel/UCSzHvd31Yub3b3rFQhykEqQ>  [https://transimpact.com/wp-content/uploads/2021/07/TI-linkedin-sig-blue.png] <http://www.linkedin.com/company/TransImpact>  [https://transimpact.com/wp-content/uploads/2021/07/TI-linkedin-sig-blue_1.png] <https://www.instagram.com/TeamTransImpact>

Inc. Magazine Inc. 5000 Fastest Growing Companies in America Ninth Year Honoree
Inc. Magazine Best Workplaces Four Year Honoree
Eastern NC Better Business Bureau Torch Award for Marketplace Ethics Four Year Honoree
Business North Carolina's Best Employer in North Carolina Four Year Honoree
2019 NC Tech Best Tech Company to Work For Award
View All Awards Here<https://transimpact.com/about-us/our-awards/>

Confidentiality Note
This message is intended only for the use of the individual or entity who is the intended recipient and may contain information that is privileged, confidential and exempt from disclosure pursuant to applicable law. If the reader of this messages is not the intended recipient, or the employee or agent responsible for delivering this message to its intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify us immediately by telephone and destroy this message. Thank you.

**Comment by christianwade** [comment]
Thank you so much Bob 🙏 and great to hear you are unblocked and ALM Toolkit his helping you achieve more
