### ISSUE TITLE
This GIt Integration Script is not looking for The new PBIP files (.PBISM &.PLATFORM) files

### ISSUE THREAD

**Issue by vinuku8** [microsoft/Analysis-Services#255]
Microsoft changed new PBIP file structure now they integrated both item.metadata.json and item. Config. Json file into . Platform file and also changeddefinition.pbidataset file to .pbism file

**Comment by RedDTG** [comment]
Hello, figured out of this issue. Import-FabricItems function is not working without this .platform file but when I save my report with a pbip format it does not create it. Is there a way to generate this file or have I to manually merge the item.metadata.json and item.config.json ?
Thanks

**Comment by RuiRomano** [comment]
Fixed on Apr 3 - commit f0402d447e2f087224a4891f4079382d7a25613e
