### ISSUE TITLE
ALM Toolkit - Error updating a model with column name changes

### ISSUE THREAD

**Issue by KNP-BI** [microsoft/Analysis-Services#258]
Hi,

I'm not sure if this is a bug or just a misunderstanding on my part.
I had made some changes to a table which mainly consisted of column name changes. 
Since that point, I've not been able to get the update to work.

Changes for reference:
Department >> Department Group
Category >> Department

```
Column '<ccon>Department</ccon>' in Table '<ccon>Department</ccon>' contains a duplicate value '<ccon>FMCG</ccon>' and this 
is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the 
primary key of a table.

Technical Details:
RootActivityId: d71a3846-cd82-412d-bc86-00dc999cd5b5
Date (UTC): 5/24/2024 4:12:41 AM
```

This error makes no sense as it is the **Department Group** that contains the **FMCG** value. 
The join is on Department (formerly Category) which contains all unique values.

What am I missing?

Thanks,
Kim

**Comment by christianwade** [comment]
Hi, this is an AS engine error. Can you try scripting the change out (use the ribbon button) and try applying it from SSMS? This might give you more internal error info.
