### ISSUE TITLE
Error during Initial Setup of Partitions

### ISSUE THREAD

**Issue by timmapuramreddy** [microsoft/Analysis-Services#28]
Hi ,

Below is the error when we try to run the AsPartitioningProcessing Solution

we have already setup all the parameter tables which are required and the application is connecting to the Source (OLAP) and target (SSAS) servers.

Solution is identifying the tables and when it tries to create the partitions below is the error.

Sequentially process       2017-07 /DataOnly

Exception message: Failed to save modifications to the server. Error returned: 'Syntax error in partition '201707' in table 'Stock_Lifting'. Token Semicolon expected. Start position: (1, 83). End position (1, 84).

Technical Details:
RootActivityId: 489f8910-e719-4a5f-b658-ede192464679
Date (UTC): 2/6/2019 11:52:37 AM
'.

Please guide us and it will be very helpful

Thanks In Advance

Regards
Mohan

**Comment by MeetGEP** [comment]
Hi, Were you able to resolve this issue? I am facing the same issue and I see that this is still open.

**Comment by MeetGEP** [comment]
I am getting this issue 
Failed to save modifications to the server. Error returned: 'Syntax error in partition 'Default Partition' in table 'Auction Document'. Token Semicolon expected. Start position: (3, 48). End position (3, 51).

Technical Details:
RootActivityId: 7e76545b-6e0e-456a-abdd-0141a21ff188
Date (UTC): 10/19/2019 2:14:14 PM
'.

**Comment by MeetGEP** [comment]
This is not an issue. There was some syntax error in partition
