### ISSUE TITLE
'MissingDefinitionParts' error when attempting to import PBIB report to workspace

### ISSUE THREAD

**Issue by denialofself** [microsoft/Analysis-Services#286]
Using the sample script 
```
# Authenticate
Set-FabricAuthToken -reset

# Ensure workspace exists
$workspaceId = New-FabricWorkspace  -name $workspaceName -skipErrorIfExists

# Import the semantic model and save the item id
$semanticModelImport = Import-FabricItem -workspaceId $workspaceId -path $pbipSemanticModelPath

# Import the report and ensure its binded to the previous imported report
$reportImport = Import-FabricItem -workspaceId $workspaceId -path $pbipReportPath -itemProperties @{"semanticModelId" = $semanticModelImport.Id}
```

Getting the following error with no indication of what its looking for or how to correct it

Existing items in the workspace: 2
Payload parts:
part: /definition.pbism
part: /diagramLayout.json
part: /model.bim
Creating a new item
Exception: Response status code does not indicate success: 400 (Bad Request).; API error
code: 'MissingDefinitionParts'

**Comment by Jtho28** [comment]
I have discovered that this is an issue with `$partPath = $filePath.Replace($itemPathAbs, "").TrimStart("\").Replace("\", "/")` in FabricPS-PBIP.psm1. I've made a change to detect the OS and trim ("/") instead on unix systems.

**Comment by RuiRomano** [comment]
Thanks! Will look into your PR.

**Comment by hettic1** [comment]
I have the same error but then running the deploy from a windows machine.
To be more precise.
Azure DevOps:
Image: windows-latest
Agent: Hosted Agent
