### ISSUE TITLE
BISM Normalizer - Log of Changes?

### ISSUE THREAD

**Issue by mattlcook** [microsoft/Analysis-Services#29]
Hi - does BISM Normalizer have a logging feature when all changes that are applied during a target update operation are saved?  

Something like the "Report Differences" feature, which generates and Excel file summary of the comparison.  This is useful, but has to be saved manually and does not necessarily represent the final changes that were applied to the target.

Thanks for any help.

**Comment by christianwade** [comment]
Hi, thanks for the feedback and sorry for the delayed response. I plan to monitor this forum more closely form now on!  Are you running from the command line? I think the optional log file contains the actions carried out
