### ISSUE TITLE
Please provide support for Power BI pbix files

### ISSUE THREAD

**Issue by mikeblakeuk** [microsoft/Analysis-Services#3]
We are looking to merge multiple pbix reports into a single Analysis Service model and want to use the compare tool to create a central model.

Ideally list the power bi 'servers' running and the databases
![image](https://user-images.githubusercontent.com/1986660/27833355-6d911bc2-60ca-11e7-89e4-43cbe2cde4bd.png)

![image](https://user-images.githubusercontent.com/1986660/27833344-5c632c5a-60ca-11e7-8721-51fe28a49c3d.png)

**Comment by christianwade** [comment]
Hi, sorry for the late reply. I would sincerely love to make this work with PBIX files. However, there are some contractual limitations to doing this. I think the situation may change in the next 2 or 3 months though ...

**Comment by LukeTeo88** [comment]
Hi Christian, hope you're well. Just wanted to check if ALM Toolkit v 5.0.1 is still expected to have issue when trying to compare between two PBI Desktop files? FYI, I'm using the Feb 2020 Power BI Desktop.

When I attempted it, it's producing the following error:
"The source is a Power BI Desktop dataset with default data-source version of PowerBI_V1, which is not supported for comparison. Please ensure you're using the latest version of Power BI Desktop and if necessary enable the preview feature."

Thanks in advance.

**Comment by christianwade** [comment]
Hi Luke, you need the enhanced metadata format that is planned to be a preview feature in Desktop as early as March

**Comment by LukeTeo88** [comment]
Awesome! Thanks Christian.
