### ISSUE TITLE
In continuation to https://github.com/microsoft/Analysis-Services/issues/302

### ISSUE THREAD

**Issue by dyutis** [microsoft/Analysis-Services#303]
I had opened the issue https://github.com/microsoft/Analysis-Services/issues/302 earlier. But seems as it is Closed, so my query which I posted later, may have been missed. 
It would be of great help if that is addressed. Thanks.

_
I have observed this condition "if ($pbirJson.datasetReference.byPath -and $pbirJson.datasetReference.byPath.path) {
" in the module script: https://github.com/microsoft/Analysis-Services/blob/master/pbidevmode/fabricps-pbip/FabricPS-PBIP.psm1. In else condition it says for byConnection just send the original.

That is where I am having trouble with. When I exported the Report using the function "Export-FabricItem", it created byConnection in the definition.pbir for the Report.
Since this belongs to byConnection, passing semanticModelId as -itemProperties not working while deploying to target workspace.

{
"version": "4.0",
"datasetReference": {
"byPath": null,
"byConnection": {
"connectionString": "Data Source=powerbi://api.powerbi.com/v1.0/myorg/;Initial Catalog=SQLDBAzureDirectQuerypbip;Integrated Security=ClaimsToken",
"pbiServiceModelId": null,
"pbiModelVirtualServerName": "sobe_wowvirtualserver",
"pbiModelDatabaseName": "",
"name": "EntityDataSource",
"connectionType": "pbiServiceXmlaStyleLive"
}
}
}
_

**Comment by dyutis** [comment]
Any update on this please?

**Comment by RuiRomano** [comment]
Thanks for reporting. Fixed this bug in commit [fc6f25a](https://github.com/microsoft/Analysis-Services/commit/fc6f25a7f9a2b43ad81b1bdf503c7f9db89de86b)

**Comment by dyutis** [comment]
> Thanks for reporting. Fixed this bug in commit [fc6f25a](https://github.com/microsoft/Analysis-Services/commit/fc6f25a7f9a2b43ad81b1bdf503c7f9db89de86b)

Thank you so much for fixing it! That resolves my issue.
