### ISSUE TITLE
ALM Toolkit 5.1.3 - "Validate Selection" not possible: "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by MaRo99382** [microsoft/Analysis-Services#313]
I am trying to deploy a local model.bim file to an existing Power BI Premium Semantic Model using ALM Toolkit.
The comparison works as expected.
However, when clicking on "Validate Selection" I receive the error "Object reference not set to an instance of an object".
My OS is set to German so the original error is "Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt", see the attached screenshot.
I have not idea what could be the issue.

- ALM Toolkit version 5.1.3 (installed via the .msi)
- Local model.bim file ("compatibilityLevel": 1560, "defaultPowerBIDataSourceVersion": "powerBI_V3")
- Remote Power BI Semantic Model in a Power BI Premium per User Workspace with "Large semantic model storage format" enabled

![Image](https://github.com/user-attachments/assets/2a366bb2-b642-4f28-b9e9-66238513556e)

**Comment by christianwade** [comment]
Thank you for raising this to my attention. I'd love to get to the bottom of this, so I can fix it. Would it be possible to share the BIM file and perhaps a BIM file representing the target model as well? If yes, please e-mail me at "chwade at microsoft dot com".
Christian

**Comment by MaRo99382** [comment]
Hi Christian,
thank you for investigating the issue.
I just send you the e-mail.

**Comment by christianwade** [comment]
Dealt with by e-mail

**Comment by conchitalaniran** [comment]
I'm also facing the same issue. Can I have support with this please?

**Comment by conchitalaniran** [comment]
I'm facing the same issue. Can I have support whit this please?

**Comment by Haboos** [comment]
Alos me facing the same issue,i am trying to migrate Azure analysis model with the new model in the same environment and i keep receiving this error : Object reference not set to an instance of an object. when i click on Validate _Selection_

**Comment by christianwade** [comment]
With the help of @MaRo99382 , I believe I have found the issue. I'm starting a full build now. It can take a couple days nowadays due to digital signing process. I'll let you know as soon as it's published ...

**Comment by christianwade** [comment]
Please try the latest release & let me know if works for you
https://github.com/microsoft/Analysis-Services/releases/tag/5.1.7

**Comment by Haboos** [comment]
Million thanks <3 it works for me

Really appriciated

**Comment by MaRo99382** [comment]
Yes, it works. Thank you!
