### ISSUE TITLE
Install without admin rights

### ISSUE THREAD

**Issue by UWE-BIDEV** [microsoft/Analysis-Services#318]
Hi @christianwade,
If I remember correctly, with previous versions I could install the ALM toolkit without admin rights, by selecting install for 'just me'.
It no longer seems possible... is it a bug? :(
Many thanks

**Comment by christianwade** [comment]
Hi, unfortunately, I don't believe this was possible. The installer hasn't changed. There are things that require admin permissions such as creating the link in the Desktop installation path to be opened as an external tool.

**Comment by christianwade** [comment]
You're welcome!
