### ISSUE TITLE
ALM Toolkit not applying changes

### ISSUE THREAD

**Issue by oscarmqz** [microsoft/Analysis-Services#319]
Hi, I've been using ALM toolkit for a while now and never had this issue before, it just started yesterday. I made changes to the SQL definition of one of my tables, then I commit the changes. The new fields do show up in the table when connected using Tabular Editor but when I refresh it, it fails because the query was not updated. I upgraded ALM to the latest version but this keeps happening. I'm manually modifying the definition with Tabular Editor and then it works fine. ALM toolkit keeps finding a difference when comparing.

**Comment by christianwade** [comment]
Hi @oscarmqz , can you check the options in the options dialog like retain partitions? SQL queries will be covered by partition definitions.

**Comment by oscarmqz** [comment]
I do use that option all the time, see attached image. That's how I keep it. I have incremental refresh set up.![Image](https://github.com/user-attachments/assets/cee36325-48cc-4a2c-9258-26e2de960bd2)

**Comment by christianwade** [comment]
I see. Can you also select "Consider partitions when comparing tables"? That should show source SQL query differences and flag those tables for updates.

**Comment by oscarmqz** [comment]
It does flag it for update but is not updating, I've tried checking that option with same result.

**Comment by christianwade** [comment]
I see. Can you share a screenshot of the differences?

**Comment by oscarmqz** [comment]
Here you go, I'm trying to add a dummy test column as an example

![Image](https://github.com/user-attachments/assets/510c1ff1-b3e3-4410-ac1d-7e76fdae6dd8)

**Comment by christianwade** [comment]
I would expect that to get updated on when doing an Update on the table. Any chance you can send me files (such as bim files, or PBIP project files, etc.) so that I can repro on my end and run it in debug mode to see what's going on?

**Comment by christianwade** [comment]
Resolved by e-mail
