### ISSUE TITLE
Model Comparison crushes, when source or target model contains Roles named other language than English

### ISSUE THREAD

**Issue by BISMN** [microsoft/Analysis-Services#33]
It shows an error " index and length must refer to a location within the string. parameter name length"

[TabularProject4.zip](https://github.com/microsoft/Analysis-Services/files/3565980/TabularProject4.zip)

**Comment by christianwade** [comment]
Hi, thanks for the feedback and sorry for the delayed response. I just tried it on the latest version and I seem unable to repro. Are you still getting this issue?

**Comment by BISMN** [comment]
Hm! Latest version... it seems to be working fine now
Thanks! ))

**Comment by christianwade** [comment]
Great!
