### ISSUE TITLE
Option to suppress prompt for the closing of the Model.BIM file

### ISSUE THREAD

**Issue by Guavaq** [microsoft/Analysis-Services#35]
Hi there, thanks for a great product.

Would it be possible to suppress the option to close the Model.bim file as shown below?

![image](https://user-images.githubusercontent.com/31457981/67054790-00ef3100-f189-11e9-973a-bf2e047234b5.png)

When making changes often, I have to click on it every time to do the comparison.

**Comment by christianwade** [comment]
Hi, thanks for the feedback and sorry for the delayed response. You want to automatically close the BIM file window without the prompt? It closes it to ensure it doesn't step on the SSDT designer's toes

**Comment by Guavaq** [comment]
No worries. Thanks for the reply. And it makes sense for the developer to always double check
