### ISSUE TITLE
No scrollbars in object definition windows

### ISSUE THREAD

**Issue by mtvessel** [microsoft/Analysis-Services#36]
The source/target object definition windows lost their scrollbars with latest update, in Visual Studio/SSDT 2017.  Vertical scrolling still works with the mouse wheel, but no scrollbars are visible.  The target definition window will scroll horizontally in response to keyboard navigation (arrow keys, home/end), but the source definition window will not scroll horizontally at all.

**Comment by christianwade** [comment]
Hi, thanks for reporting this. I seem unable to repro. There are HDPI issues with Winforms extensions running in VS in general. I raised with the VS team a while ago, but it's been a journey. The customized HDPI fixes for WinForms extensions seem unpredictable, especially when tried on different machines, to put it nicely. If I get any update of way to repro and fix, I will

**Comment by Guavaq** [comment]
Thanks for the reply. Hopefully the win forms update will work.

I often just click on one of the items and then scroll through with the mouse wheel

**Comment by mtvessel** [comment]
Thanks, Christian.  I searched around and fiddled with various Win 10 HDPI settings, to no avail.  Then a Windows update came through and the scrollbars have returned!  I have no idea what fixed it, I can only hope it sticks.

**Comment by christianwade** [comment]
Thanks for letting me know, and yes, let's hope it sticks! It may be a VS behavior or update.
