### ISSUE TITLE
BISM Normalizer 5 appears to not escape JSON sequences correctly?

### ISSUE THREAD

**Issue by jdfancke** [microsoft/Analysis-Services#38]
Did not have this issue previously with BISM Normalizer 4.

![Capture](https://user-images.githubusercontent.com/20044040/70575710-2d5c8200-1bfb-11ea-8979-22c26dff903b.PNG)

The error occurs when trying to start a new compare. The error stops the compare from starting, effectively meaning you can't do a compare.

**Comment by christianwade** [comment]
Hi, is it OK if you can e-mail me the bim file so I can repro? chwade at ms dot com or private message me on twitter. Thanks
