### ISSUE TITLE
Any approach to get Analysis services data from REST API?

### ISSUE THREAD

**Issue by NaveenaG-UI** [microsoft/Analysis-Services#41]
Please help me with options..

**Comment by christianwade** [comment]
Hi, the REST API is for processing/sync operations. We have this client lib for getting data.
https://www.nuget.org/packages/Microsoft.AnalysisServices.AdomdClient.retail.amd64/

If you need a non-.NET web interface, you can look at this:
https://github.com/microsoft/azure-analysis-services-http-sample
