### ISSUE TITLE
ALM Toolkit - Report Differences error opening Excel 64-bit

### ISSUE THREAD

**Issue by rudzimj** [microsoft/Analysis-Services#42]
In ALM Toolkit version 5.0.1, when I click the Report Differences button, I receive:

Unable to cast COM object of type 'Microsoft.Office.Interop.Excel.ApplicationClass' to interface type 'Microsoft.Office.Interop.Excel._Application'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{000208D5-0000-0000-C000-000000000046}' failed due to the following error: Error loading type library/DLL. (Exception from HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY)).

I am using Excel Version 1902 (Build 11328.20480 Click-to-Run) 64-bit

**Comment by christianwade** [comment]
Hi, my Excel installation is 32 bit which may be why not getting this issue. When I web searched that error, it seems 64 bit installations should work even if run as 32 bit, but sometimes need to modify the installation/configuration. There were a handful of solutions to modify the installation/configuration, so not sure exactly which one would work for you. Sorry can't be of more help right now, but let me know if you find a solution!

**Comment by rudzimj** [comment]
I installed 64-bit at home and it works fine. Something is wrong with my Office install at work. I have been trying every repair and cleanup tool for Office and haven't hit the right thing yet. I'll keep working on it!

**Comment by rudzimj** [comment]
Got it! This registry key was wrong: **Computer\HKEY_CLASSES_ROOT\TypeLib\{00020813-0000-0000-C000-000000000046}\1.9\0\Win32**. It pointed to the 32-bit version of Office which had been removed. I changed the path to the 64-bit folder and it works now.

**BEFORE:**
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{00020813-0000-0000-C000-000000000046}\1.9\0\Win32]
@="C:\\Program Files (x86)\\Microsoft Office\\Root\\Office16\\EXCEL.EXE"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{00020813-0000-0000-C000-000000000046}\1.9\0\Win64]
@="C:\\Program Files\\Microsoft Office\\Root\\Office16\\EXCEL.EXE"
```
**AFTER:**
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{00020813-0000-0000-C000-000000000046}\1.9\0\Win32]
@="C:\\Program Files\\Microsoft Office\\Root\\Office16\\EXCEL.EXE"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{00020813-0000-0000-C000-000000000046}\1.9\0\Win64]
@="C:\\Program Files\\Microsoft Office\\Root\\Office16\\EXCEL.EXE"
```

This page was helpful in figuring out this error: https://social.technet.microsoft.com/wiki/contents/articles/18919.c-troubleshooting-unable-to-cast-com-object-of-type-microsoft-office-interop-powerpoint-applicationclass.aspx
