### ISSUE TITLE
level of 1500 is below the minimal compatability level of 2147483647

### ISSUE THREAD

**Issue by f-benoit** [microsoft/Analysis-Services#43]
I've recently installed SSAS 2019 and deployed few tabular models using the 1500 compatibility.

When I try to process the db from SSMS I get the following error message:

"The database compatibility level of 1500 is below the minimal compatability level of 2147483647 needed..."

My SSAS version 15.0.32.52

**Comment by f-benoit** [comment]
![image](https://user-images.githubusercontent.com/1439376/73784945-9cd39580-4796-11ea-9864-833018538511.png)

**Comment by f-benoit** [comment]
sorted.
I've upgraded SSMS to the 18 version

**Comment by otykier** [comment]
For anyone else encountering this and unable to upgrade to the latest version of SSMS, you can workaround this issue by scripting the process job and executing the TMSL script in an XMLA query window.
