### ISSUE TITLE
Cannot deploy using BISM Normalizer to AAS

### ISSUE THREAD

**Issue by Guavaq** [microsoft/Analysis-Services#46]
Hi there Christian,

I thought I would let you know that I have been tyring to use the BISM Normalizer to deploy an update to an AAS database.
I ran query profiler and I got the following error message which I thought would be good for you to see.

![image](https://user-images.githubusercontent.com/31457981/75124549-b31ca380-56fb-11ea-8e90-fab4a1b10c7a.png)

**Comment by christianwade** [comment]
Hi Gilbert, thanks for letting me know. I've forwarded to engineering. Might be difficult to repro without the model that is causing the error (feel free to ping me it if you have it)

**Comment by Guavaq** [comment]
Thanks Christian,

I have tried the query on both SSAS On-Prem 2017 and on AAS and both give me the same error. It would appear that it might not be the model causing the issue?

Or do you think there is something in particular in my dataset causing the issue?

The query is: 
select * from $SYSTEM.DISCOVER_CALC_DEPENDENCY

**Comment by christianwade** [comment]
Hi Gilbert, yeah I suspect it's some specific metadata that is in the dataset. Would you perhaps be able to send me the BIM file? I'm about to e-mail you ...
