### ISSUE TITLE
Feature request: Ignore white space option

### ISSUE THREAD

**Issue by q0-0n** [microsoft/Analysis-Services#5]
A great feature would be to ignore formatting when comparing code. If someone updated only the formatting of the code, the whole section gets highlighted as a change. 

I would like to ignore the formatting and be able to see only real changes to the code.

**Comment by christianwade** [comment]
Sorry for the late reply. Thanks for the suggestion. I believe the only whitespace that can be user modified is in DAX code. The JSON is serialized by the engine based on the metadata, so I think user changes won't take effect
