### ISSUE TITLE
The JSON DDL request failed with the following error: The 'Name' property cannot contain any of the following characters

### ISSUE THREAD

**Issue by jiteshparwal93** [microsoft/Analysis-Services#51]
When I am trying to deploy differential change, its failing with error "The JSON DDL request failed with the following error: The 'Name' property cannot contain any of the following characters"
I have checked my column & measure names, none of it contain mentioned special character.

**Comment by christianwade** [comment]
This is a known bug. The fix is waiting to be deployed but held up by deployment freezes due to the current climate.

The workaround is to remove special characters from **all database names** in the workspace (not just the one you're deploying to).

If you choose to use the workaround, can you confirm it worked for you?

**Comment by kpsdk** [comment]
I was having having this error with Power BI ALM Toolkit 5.0.5.  On the service I renamed two datasets with parentheses in the name.  That DID NOT resolve the problem, but when I deleted the datasets I was able to successfully UPDATE the model on the service from the Power BI ALM Toolkit application.
Thank you!

**Comment by dufrenoyl** [comment]
Thank you for the context and workaround (I removed special characters and it worked)
This is not happening if pushing datasets to PowerBi Services (using TOM API) but only to my local instance of Analysis Services.
Same behavior is expected on both platforms I guess.

Ticket has been closed; can we still expect a fix?
Thank you @christianwade

**Comment by christianwade** [comment]
The fix I was referring to in the thread was actually for Power BI (not on prem SSAS). It seems the Power BI one has been fixed. For on-prem SSAS, unless we specifically choose to include in a service pack, changes normally show up in the next major version. We are due a major version of SSAS soon, so I'd expect it there.
