### ISSUE TITLE
BISM normalizer - error after Validate Selection

### ISSUE THREAD

**Issue by Pawel-Laszcz** [microsoft/Analysis-Services#52]
Hello, 

Issu apears once I click Validate Selection , 
re-install of BISM didnt helped to solve this :( 

![image](https://user-images.githubusercontent.com/63453399/80341942-a0415f00-8863-11ea-90fd-35203872de37.png)

**Comment by christianwade** [comment]
Hi, I've been trying to reproduce this on my development environment for a long time. It has been reported to me by a handful of people. They have sent me the project and BISM files and I was still unable to reproduce it. I even went as far as installing the whole development environment on one of their machines and when I ran it in debug mode, it didn't repro :(.

To get past this, perhaps one of the following options?

- See if there is a VS update or something you can apply. Others told me that it went away for some reason.
- Use the ALM Toolkit instead as a workaround (till hopefully this goes away as it has for others). You should be able to download the installer from [here](http://alm-toolkit.com/). If you use ALM Toolkit, you should be able to select SSDT projects in the "PBI Desktop" dropdown that are currently open with BIM file open in VS.

**Comment by Pawel-Laszcz** [comment]
Hi,

Yes - I didnt saw the updets - once I run them issue was resolved. 
Thank you for quick response !

-- 
Regards, Pawel
