### ISSUE TITLE
Invoke-AsCmd does not work with quote in passwords

### ISSUE THREAD

**Issue by fmms** [microsoft/Analysis-Services#54]
Hi,

I think i found a bug in Invoke-AsCmd.

I am using the following code snippet:

```        
$asAdminPassword = @'
This"is"aPassword%$%
'@ -replace '"', '""'
$SECURE_PASSWORD = ConvertTo-SecureString $('"{0}"' -f $asAdminPassword) -AsPlainText -Force
$CREDENTIAL = New-Object System.Management.Automation.PSCredential ("aaaa@bbb.com", $SECURE_PASSWORD)
Invoke-ASCmd -InputFile "adjustconnection.tmsl" -Server "asazure://westeurope.asazure.windows.net/ccc:rw" -Credential $CREDENTIAL
```

Without the extra quotes arround the password, I get the following error
```
A semicolon was expected at index 133 in the connection string.
```

Adding quotes arround the password that are not even part of the password works arround the issue, but certainly does not feel correct.

Thanks

**Comment by christianwade** [comment]
Just catching up. If still an issue, please raise a support ticket with either AAS/SSAS/Premium
