### ISSUE TITLE
The JSON DDL request failed with the following error: Cannot convert value '21/04/2020 10:20:00' to required type 'String'. Check path 'model.tables[0].partitions[0].annotations[0].value

### ISSUE THREAD

**Issue by nonmanifold** [microsoft/Analysis-Services#57]
When calling Server.Execute(string command) with JSON that has valid ISO 8601 datetime in partition's annontation, in this case "value": "2020-04-21T10:20:00"
The following error is thrown:
"The JSON DDL request failed with the following error: Cannot convert value '21/04/2020 10:20:00' to required type 'String'. Check path 'model.tables[0].partitions[0].annotations[0].value'

Library version
Microsoft.AnalysisServices.retail.amd64.18.7.0.1

**Comment by christianwade** [comment]
Hi, does it repro from SSMS using a createOrReplace TMSL script creating the db (not pre-existing)? If yes, can you send me the file so we can debug?

**Comment by nonmanifold** [comment]
When generating script for existing DB from SSMS 18.5 (GA) annotations get mutated, but it does not cause the process to fail:
here is what gets generated:

[re-create db (generated by SSMS 18.5).xmla.txt](https://github.com/microsoft/Analysis-Services/files/4655819/re-create.db.generated.by.SSMS.18.5.xmla.txt)

compare it to what I believe it should look like with annotations untouched
[re-create db with correct annotations.xmla.txt](https://github.com/microsoft/Analysis-Services/files/4655822/re-create.db.with.correct.annotations.xmla.txt)
And TabularEditor (https://github.com/otykier/TabularEditor) correctly sees annotations as strings they are:
![image](https://user-images.githubusercontent.com/537770/82429714-460f7480-9a84-11ea-89ae-48615a722779.png)
To work around this, I'm just prepending annotation value with its name and that stops serializer from treating them as datetimes.

hope this helps to reproduce and debug.
Thank you.

**Comment by christianwade** [comment]
I can see annotations like the following in both the files. They are not shown in the comparison dialog, but IIRC they are retained for model updates

                "annotations": [
                  {
                    "name": "QueryEditorSerialization"
                  },
                  {
                    "name": "LoadedOn",
                    "value": "2020-03-01T10:20:00"
                  }
                ]

**Comment by nonmanifold** [comment]
yes you are correct, these annotations we want to use for storing our metadata.
These annotations seem to be implicitly parsed and converted to DateTime instances and then converted back to string (that makes them loose zeroes on the end), and during JSON DDL generation instead of silent conversion an error happens. I expected that annotations should always be treated as strings and left unmodified.
I was able to prevent implicit conversion loop from happening, by putting some garbage at the beginning of their values.
Please correct me if I'm wrong and annotation values should be wrapped into for example XML , or there is a more correct way of protecting them from mutations

**Comment by christianwade** [comment]
IIRC there was a good reason why the annotation was stripped out of the JSON string used for comparison :). At minimum it could cause objects to be listed as different due to internal annotations set by Power BI.

I'll keep it in mind as to whether I could create an option to not strip out the annotations, but I'd have to look into it.
