### ISSUE TITLE
Unclear what target Workspace info to specify ("unsupported data format : text/html; charset= utf-8")

### ISSUE THREAD

**Issue by fordmaxson** [microsoft/Analysis-Services#58]
I am a Power BI user attempting to implement incremental refresh and running into the issue defined at the bottom of https://docs.microsoft.com/en-us/power-bi/admin/service-premium-incremental-refresh.

I would like to use ALM Toolkit to update my BI report (charts, measures, etc.) while leaving the underlying dataset alone on the server (which has been incrementally accruing data).

When it asks for a target workspace and I enter something like "https://app.powerbi.com/groups/76288xxx-26xx-4cxx-a7xx-xxxxxxxxxx"
I get 
"unsupported data format : text/html; charset= utf-8"

I am not clear on where to go to get the correct workspace string and what format you are looking for.

Thanks for the help.

**Comment by dylanjmorgan** [comment]
Try
powerbi://api.powerbi.com/v1.0/myorg/<Name of workspace>
________________________________

**Comment by fordmaxson** [comment]
Thanks for response.
That got me a "ClaimsToken Authority Not Found"

Is there any supporting installs required?   Where does my login and password come into play here?

**Comment by christianwade** [comment]
Is your workspace on a Premium capacity? (xmla only works on Premium). If yes, Dylan's format is correct, but you can confirm by copying from the workspace settings. 
https://docs.microsoft.com/en-us/power-bi/admin/service-premium-connect-tools#connecting-to-a-premium-workspace

**Comment by fordmaxson** [comment]
OK, I am not on Premium, but we have purchased Embedded via an A1 server on Azure.
I dug through more of your documentation and went and installed Visual Studio Community and installed the 2 extensions.  At that point I just left it running.  Have not pulled any code into Visual Studio.

So success!  I am now able to get ALM Toolkit to run a comparison between my pbix on Desktop and what has been Published.

I inserted a simple text box into my pbix report view.  Unfortunately, I see nothing in the comparison tool that caught this.  My goal is to leave all the data alone and just send up the new page with the new text box.

Help?

![image](https://user-images.githubusercontent.com/38134430/83057895-88f1bf00-a025-11ea-9a4a-77cbff80b5e4.png)

**Comment by christianwade** [comment]
Great. Glad you got past that hurdle.

If you're on Premium (including A skus) you shouldn't even need VS or the extensions if all you want to do is run ALM Toolkit.

It won't pick up (or deploy) report changes. It's only for datasets. You may want to copy the visuals into a separate live connect report to separate it from the dataset for ease of redeployment. Deploying the report alone normally doesn't have much overhead

**Comment by fordmaxson** [comment]
Very frustrating, Microsoft keeps having us have to upgrade, change, switch to something else to get features working.  The doc at https://docs.microsoft.com/en-us/power-bi/admin/service-premium-incremental-refresh should be updated to indicate ALM can't update just the report.  It's misleading and the whole point should be how do you update the report without messing up the dataset that used incremental refresh.

Our datasets query mySQL.  Not sure if I can do a live connect report as a result.  Also not sure if live connect is available on our embedded A1, if there is a cost impact, performance impact.  More research and hunting...sigh

Thank you for your help though.

**Comment by christianwade** [comment]
That's a fair point about updating the documentation about this. I'll submit the request today.

There are technical reasons why XMLA write doesn't work on Pro. We could enable read only access, but currently focusing on getting it (& large models) to GA.

Not sure I understand the live connect over mySQL scenario, but there should be no feature loss on an A1 AFAIK
