### ISSUE TITLE
Error comparing Project to DB:  Index and length refers to a location within the string

### ISSUE THREAD

**Issue by waltheed** [microsoft/Analysis-Services#59]
I am re-posting the message from Rudy Cassel , posted in marketplace.visualstudio.com.
I encountered the same issue. 

---------------------------
This is an issue on both VS 2017 and VS 2019 Tabular, when I try to compare code using BISM Normalizer :

from Source: Server to Target: Project I DON't get any errors.

However when I flip the comparison from source: Project to Target: server then the error is: Index and length refers to a location within the string. Parameter name: length.

It seem I can only read from server not write when I use this tool, though I can deploy to the server through VS deployment configuration.

If i create a new model this works, however an existing model it gives me the errors.

Let me know if I'm missing something on the server set up or BISM too.

Thanks
By Rudy Cassel Thursday

---------------------------

![bism error](https://user-images.githubusercontent.com/16383207/84515972-74702080-accd-11ea-9728-cdbdc81ef4c8.png)

Thanks, 
Edgar Walther

**Comment by christianwade** [comment]
Hi Edgar, I'm working with Rudy on another thread trying to get a repro on the dev environment so it can be debugged and fixed. Do you have a repro based just on solution files you can send me by e-mail?

Thanks,
Christian

**Comment by waltheed** [comment]
Hi Christian,

Thanks for your reply.

I do not have it all available as just solution files. I will need to find some time to prepare that.


Best regards,

Edgar Walther
ITsmart
www.itsmart.nl<http://www.itsmart.nl/>

[cid:image005.png@01D642FF.833DD6D0]

   [cid:image007.jpg@01D15395.610D7740] <https://nl.linkedin.com/in/edgarwalther>    [cid:image008.png@01D15395.610D7740] <https://twitter.com/edgarwalther>    [cid:image009.png@01D15395.610D7740] <http://paper.li/edgarwalther/1421271985>

**Comment by waltheed** [comment]
Hi Christian,

I have some time now to assist with this issue. It’s also annoying enough for me to spend time on it 😊

Do you want to have a screen sharing session maybe?
What kind of files would you need to analyze this?


Best regards,

Edgar Walther
+31 6 3449 2516
ITsmart
www.itsmart.nl<http://www.itsmart.nl/>


[cid:image008.jpg@01D6B789.71AC2D00]<https://nl.linkedin.com/in/edgarwalther>   [cid:image009.png@01D6B789.71AC2D00] <https://twitter.com/edgarwalther>    [cid:image010.png@01D6B789.71AC2D00] <http://paper.li/edgarwalther/1421271985>


From: Edgar Walther (ITsmart)
Sent: maandag 15 juni 2020 10:27
To: microsoft/Analysis-Services <reply@reply.github.com>; microsoft/Analysis-Services <Analysis-Services@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [microsoft/Analysis-Services] Error comparing Project to DB: Index and length refers to a location within the string (#59)

Hi Christian,

Thanks for your reply.

I do not have it all available as just solution files. I will need to find some time to prepare that.


Best regards,

Edgar Walther
ITsmart
www.itsmart.nl<http://www.itsmart.nl/>

[cid:image004.png@01D6B789.719AC7E0]

   [cid:image005.jpg@01D6B789.719AC7E0] <https://nl.linkedin.com/in/edgarwalther>    [cid:image006.png@01D6B789.719AC7E0] <https://twitter.com/edgarwalther>    [cid:image007.png@01D6B789.719AC7E0] <http://paper.li/edgarwalther/1421271985>

**Comment by christianwade** [comment]
Hi Edgar, sorry for the delayed response.

Ideally I'd get a repro on my environment. I'd like to get the error in debug mode so I can see what's going on.

Are you able to repro it using a source and target that are both projects in the solution in SSDT? If yes, can you send me the whole solution with the files?
