### ISSUE TITLE
not able to comparision between desktop and power Bi service

### ISSUE THREAD

**Issue by NamsAssured** [microsoft/Analysis-Services#60]
Getting following error while comparing desktop and service file.
The source is a Power BI Desktop dataset with default data-source version of PowerBI_V1, which is not supported for comparison. Please ensure you're using the latest version of Power BI Desktop and if necessary enable the preview feature.

Power Bi desktop running on Jun 2020 version
ALM Toolkit on version 5.0.7

**Comment by christianwade** [comment]
Hi, can you please enable "enhanced dataset metadata" in the preview features dialog?

**Comment by NamsAssured** [comment]
Thanks Christian,  I did it and it works!! thanks

**Comment by christianwade** [comment]
Sounds good!
