### ISSUE TITLE
Validation error for Text only DAX measure and commented DAX

### ISSUE THREAD

**Issue by herbalt** [microsoft/Analysis-Services#62]
Facing an issue where I have a measure that is only text (that hasn't been changed in source or target), that is causing the Validate Selection to fail. 

I had another measure also failing that had a comment line referencing some columns in the model that also was causing a validation issue. This issue went away went I removed the commented line of DAX. This error was stating that it couldn't find the measure/column in the target model too (similar to the screenshot). 

![ALM Issue](https://user-images.githubusercontent.com/5960777/88185865-57176600-cc2c-11ea-9180-3276ac63df88.PNG)

**Comment by christianwade** [comment]
Thanks, I've added to the todo list to take a look when I get the chance.

BTW, the calculation dependencies warning does not affect the actual actions, so it does not make any difference to the actions performed on the target model. I'm considering making them informational so this is clearer.
