### ISSUE TITLE
When can we have the ability to merge code between two PBIX file

### ISSUE THREAD

**Issue by xushuo1987** [microsoft/Analysis-Services#64]
This is more like a question instead of an issue. When we try to validate metadata between two PBIX files, for Table, Relationship and etc. there is always a warning message saying because the target is a PowerBI desktop file or PBIT template, modifications for these types are not supported yet. Do we have an ETA for this feature to become available? That would be super handy for us.

Thanks so much

**Comment by christianwade** [comment]
Thanks for the feedback. We are very keen to get this done too. It is planned to start soon, but it's a lot of work to completely harden Desktop to external model changes so we don't have an ETA right now
