### ISSUE TITLE
(Question) Using BISMNormalizer for Azure Devops Pipeline

### ISSUE THREAD

**Issue by Daandamhuis** [microsoft/Analysis-Services#66]
Hi Christian, 

Is their a Wiki page on how to use the BISM Normalizer on the CLI? I could use it in conjunction with the Tabular Editor to check for Defintion changes before proceeding with Schema Validation, Processing and Syncing. 👍

**Comment by Geraldziu** [comment]
The CLI and a lot more is coverd in this white paper https://github.com/microsoft/Analysis-Services/blob/master/BismNormalizer/Model%20Comparison%20and%20Merging%20for%20Analysis%20Services.pdf

Correct me if I'm wrong but I think that the Tabular Editor can do a comparison on its own. This whole process is covered in this blog post https://tabulareditor.com/2019/02/20/DevOps1.html

**Comment by christianwade** [comment]
That whitepaper is the best resource for CLI of BISM Normalizer. Let me know if you have questions.

**Comment by Daandamhuis** [comment]
> That whitepaper is the best resource for CLI of BISM Normalizer. Let me know if you have questions.

Is it possible to compare a BIM file to a model deployed on a server via the CLI and without creating the BSMN file?

> My current process is to generate a BIM file based on the Master Model Pattern and then deploy that specific BIM file to the processing server where it will be processed and eventually synced to a production server.

**Comment by christianwade** [comment]
The CLI requires a BSMN file. You could in theory create one (or parameterize one) to be used
