### ISSUE TITLE
Method not found when comparing models

### ISSUE THREAD

**Issue by JaccodeZwart** [microsoft/Analysis-Services#67]
Hi there,

When comparing model (file based) I get the message : 

Method not Found: 'Microsoft.AnalysisServices.Tabular.Model 
Microsoft.AnalysisServices.Tabular.Model.Database.get_Model()

This is my Visual Studio info :  
Microsoft Visual Studio Community 2019
Version 16.7.1
VisualStudio.16.Release/16.7.1+30406.217
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Community

Microsoft Visual Studio Tools for Applications 2019   00435-60000-00000-AA743
Microsoft Visual Studio Tools for Applications 2019

#ProductName   1.6.16
#ProductDescription

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.7.532.28833
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2035807+72d099b977d3a85e65fa3b0614ca8cfc803fef02
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.7.532.28833
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.7.532.28833
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.4.6000.1
Microsoft Azure Data Lake Tools for Visual Studio

Azure Stream Analytics Tools for Visual Studio   2.4.6000.1
Microsoft Azure Stream Analytics Tools for Visual Studio

BI Developer Extensions for Visual Studio 2019   2.3.9
BI Developer Extensions v2.3.9 for Visual Studio 2019 - An add-in to extend SQL Server Data Tools

BISM Normalizer   3
BISM Normalizer manages Analysis Services tabular models

C# Tools   3.7.0-6.20375.2+34202cc2f3e869fd70a26d8237f4552cf9e192cf
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   2.11.104.25275
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Microsoft Azure HDInsight Azure Node   2.4.6000.1
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.4.6000.1
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.4.6000.1
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30701.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.79+ge3567815aa.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NuGet Package Manager   5.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Project   1.0
Information about my package

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Analysis Services   15.0.19215.0
Microsoft SQL Server Analysis Services Designer 
Version 15.0.19215.0

SQL Server Data Tools   16.0.62008.03130
Microsoft SQL Server Data Tools

SQL Server Integration Services   15.0.2000.123
Microsoft SQL Server Integration Services Designer
Version 15.0.2000.123

SQL Server Reporting Services   15.0.19124.0
Microsoft SQL Server Reporting Services Designers 
Version 15.0.19124.0

SsmsVsIntegration   1.0
Information about my package

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.20702.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.7.0-6.20375.2+34202cc2f3e869fd70a26d8237f4552cf9e192cf
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

I allso get the message that a extension is not loaded because of use of depreceted methods.

What can be wrong ??

Jacco

**Comment by warthurton** [comment]
I'm having the same issue.  It seems to be known.

> Hi, I have been unable to repro this. Apparently it may be caused by an SSDT bug with SSIS as some users reported that uninstalling the SSIS extension resolved it. Please let me know if you experience the same. If you want to send me the project files (assuming it repros locally without a connection to the server), I'm happy to try
> By Christian Wade 7/28/2020

https://marketplace.visualstudio.com/items?itemName=ChristianWade.BISMNormalizer3&ssr=false#qna

**Comment by JaccodeZwart** [comment]
I have uninstalled the SSIS extension and now it works just fine.

On the other hand it introduced a new issue . . .  How do I create and maintain SSIS projects in Visual Studio now that the SSIS extension is uninstalled in order to get BISMNormalizer working ?? ? Think we have to wait until the SSDT bug is resolved I guess.

**Comment by pankajpandya** [comment]
I had the same issue. Instead of uninstalling, i just disabled SSIS extension and it worked. Now whenever i have to use SSIS , i just need to re-enable SSIS before using. Its annoying but works quite well.

**Comment by christianwade** [comment]
Yeah, unfortunately I have raised this multiple times to the SSIS team but they haven't taken any action on it.

**Comment by MickealpDavis** [comment]
Your not orphans,

I,m having the same problem.  i might try installing an older version of the SSIS extension and see what happens.

**Comment by MickealpDavis** [comment]
Hi All,
Its a known problem with the SSIS 3.12 install.
I wasted one o my two support calls when i should have read the release notes for 3.12 :-(

Suggest you download SSIS 3.11.1

https://marketplace.visualstudio.com/items?itemName=SSIS.SqlServerIntegrationServicesProjects

**Comment by christianwade** [comment]
Thanks Mickeal for the suggestion.

This issue seems to keep coming up. For those affected, please feel free to raise a bug with the SSIS team. They need to fix their installer. There have been other (non-BISM related) manifestations of the same bug.

**Comment by hamzamedi** [comment]
The 

> Hi All, Its a known problem with the SSIS 3.12 install. I wasted one o my two support calls when i should have read the release notes for 3.12 :-(
> 
> Suggest you download SSIS 3.11.1
> 
> https://marketplace.visualstudio.com/items?itemName=SSIS.SqlServerIntegrationServicesProjects

SSIS 3.11.1 is not available anymore and i'm still getting this problem in the newest version. 
How can i solve this issue?

The error i'm getting:

Error: 0x0 at Azure Blob Download Task, Azure Blob Download Task: Download task has stopped with exception: Method not found: 'Microsoft.WindowsAzure.Storage.Blob.CloudBlobClient Microsoft.DataTransfer.Runtime.AzureBlobConnectorHelper.CreateBlobClient(System.Collections.Generic.IDictionary`2<System.String,System.Object>)'.
Task failed: Azure Blob Download Task
