### ISSUE TITLE
Unable to upgrade from 1520 Compatibility Level to 1535

### ISSUE THREAD

**Issue by evnpresson** [microsoft/Analysis-Services#68]
I'm getting an error when I try to compare a model in Power Bi service with XMLA Read/Write activated in Premium capacity to a model in Power Bi desktop. I get a popup error saying "Source compatibility level 1535 is higher than the target 1520, which is not supported for comparison". Usually this type of popup asks for the user to upgrade the current compatibility level to match the source but this isn't showing up. I can't seem to figure out how to upgrade the PBI Desktop model to 1535 but all of my models in PBI Service are now at 1535 compatibility level. 

![image](https://user-images.githubusercontent.com/69851062/90509323-25a89200-e127-11ea-9620-8836d0c19193.png)

**Comment by christianwade** [comment]
Hi, it doesn't offer compat level upgrade if the target is Power BI Desktop because Desktop isn't hardened to external model changes like changing the compat level yet. Even if it were at 1535, there is only a limited number of changes you can make to Desktop till the hardening work is done. What changes are you trying to add to the Desktop file?

**Comment by evnpresson** [comment]
I'm attempting to align my local desktop version of my PBIX with my service version. I've pushed some changes to my service version which I need to push into my desktop version as well.  I can't download the PBIX from the service because it has incremental refresh enabled which prevents it. I like to use ALM toolkit to merge changes from different models (like copying DAX measures).

**Comment by evnpresson** [comment]
Perhaps my issue is more that I don't know how to update/modify the compat level within a PowerBi desktop PBIX. In addition to the above situation with the service, I also have one PBIX that is at 1535 compat level that I'd like to merge into another PBIX with a 1520 compat level. If I knew how to update the compat level, I would do it manually for the 1520 PBIX.

**Comment by christianwade** [comment]
Power BI Desktop upgrades the compat level on demand when you use a feature that requires dataset metadata in a higher compat level than the current one. A workaround would be to find the feature you used for the 1535 PBIX and apply it to the 1520 PBIX to upgrade it.

I'm pretty sure if you try to upgrade the compat level in TOM (which technically you can do), it would break Desktop.

**Comment by evnpresson** [comment]
The problem is that I have no idea what features were used to drive the compat level up to 1535. From everything I've checked, the two PBIX files are very similar. How can I figure out which features drive which compat levels?

**Comment by christianwade** [comment]
We don't keep a public log of that, but I could investigate with the dev team. 
What modeling things are you trying to push to the PBIX? Please remember that even with the right compat level, it currently only works for measures, calc groups and perspectives if the target is a PBIX

**Comment by evnpresson** [comment]
Indeed those are the only things I'm trying to merge between the two PBIXs (measures and calc groups). If I had a simple list of features by compat level, I could figure out which ones are missing from the 1520 level PBIX and add them. Thank you for the help!

**Comment by christianwade** [comment]
I'll see if I can track down a list. You could also try this, which might work: in Tabular Editor, put a checkmark in the “Allow unsupported Power BI features” option, and then going into the model properties to manually replace the compat level with a higher value.
Please take a backup of the PBIX before you do this and test it.

**Comment by evnpresson** [comment]
That worked! Or at least ALM Toolkit no longer has an error and I'm able move forward. What are the repercussions of manually changing the compat level in the model?

**Comment by christianwade** [comment]
Great news! Hopefully there are not repercussions, but since it's not supported, we can't guarantee it (so please keep a backup of the PBIX)
