### ISSUE TITLE
No Room Available to Display Rows on Validating Selection

### ISSUE THREAD

**Issue by dylanjmorgan** [microsoft/Analysis-Services#7]
When Validating Selection getting a modal showing No Room Available to Display Rows.  Consistant behavoir on either 1200 or 1400 models, re downloaded today.

**Comment by christianwade** [comment]
I'd love to get a repro :). Since this is environmental, need to set up (VS2017) debug environment on machine that is causing this

**Comment by dmayi** [comment]
I hit this issue all of a sudden on SSDT 2017 v15.9.24. It will not go away even after installing/re-installing BISM Normalizer extension.  
**SOLUTION:** I completely uninstalled and re-installed SSDT, then the extension.

**Comment by christianwade** [comment]
For reference: https://github.com/microsoft/Analysis-Services/issues/44
