### ISSUE TITLE
ALM Toolkit validation flags measures with square brackets in comments

### ISSUE THREAD

**Issue by aarongiust** [microsoft/Analysis-Services#71]
The validation in the ALM Toolkit will flag measures that use square brackets in either comments in the DAX or in hardcoded values in expressions thinking they are column references when they are not. See screenshot below.

![image](https://user-images.githubusercontent.com/656550/91989317-647d4100-ecfe-11ea-909f-c7beeee4b1f1.png)

**Comment by christianwade** [comment]
Thanks for logging this. I do have it on my todo list but haven't got to it yet. BTW, the measure dependencies don't affect anything if you ignore the warning (they are not blocking). I'll try to get to it ....

**Comment by ttroutwine** [comment]
I experienced the same issue and it took me a few hours to find this gem explaining it.  I hope this gets resolved.
