### ISSUE TITLE
ALM Toolkit generates whole database script instead of just changes

### ISSUE THREAD

**Issue by aarongiust** [microsoft/Analysis-Services#72]
The ALM Toolkit generates a script for the entire database but really should only do that when the database does not yet exist. Otherwise, it should create a script that only makes changes to the destination...or at least give the user the option to generate changes only or the whole database.

**Comment by christianwade** [comment]
Partial update scripts would be good, but only a small amount of tabular objects allow updates in isolation in a TMSL script
