### ISSUE TITLE
PowerBI_V1 not supported: using Sept 2020 PBI desktop release

### ISSUE THREAD

**Issue by JoshFlory** [microsoft/Analysis-Services#75]
I am using the PBI Desktop Version: 2.85.681.0 64-bit (September 2020).

I am trying to use ALM toolkit to do a compare and it throws the error,
"The source is a Power BI Desktop dataset with default data-source version of PowerBI_V1, which is not supported for comparison.  Please ensure you're using the latest version of Power BI Desktop and if necessary enable the preview feature."

There does not appear to be any relevant preview feature to enable in this new version of PBI?

**Comment by christianwade** [comment]
Hi, is the upgrade to V3 in the Sept Desktop release failing? If the upgrade failed, you should see a red warning bar across the report canvas indicating that the report still needs to upgrade to V3 – if clicking “Upgrade” fails then we’ll need more details to investigate. 

If yes, can you please raise a bug at https://powerbi.microsoft.com/en-us/support/ The Desktop team would appreciate it if you can send them your PBIX to diagnose.

**Comment by JoshFlory** [comment]
There is no error, but for whatever reason PBI Desktop is only saving my files as 1465 level.  I submitted a ticket, thank you!

*Session data:
Release:
September 2020

Product Version:
2.85.963.0 (20.09) (x64)


Model Default Mode:
Empty

Model Version:
PowerBI_V1

Is Report V3 Models Enabled:
True
