### ISSUE TITLE
Error on "Validate Selection"

### ISSUE THREAD

**Issue by jkapoio** [microsoft/Analysis-Services#77]
When clicking on "Validate Selection", ALMTK displays an error message: "Calc dependencies infinite 
![Validate Selection Error](https://user-images.githubusercontent.com/72085764/94568843-64138f80-0243-11eb-9852-710efed051ab.png)
[models (.bim) - source and target.zip](https://github.com/microsoft/Analysis-Services/files/5299546/models.bim.-.source.and.target.zip)

detected for type 'DataSource', table" ", name" Oracle / ORABI "."

This error occurs in two Fact tables: "PR_ACOMP_QUALIDADE_COMB" and "PR_ACOMP_QUALIDADE_PTOV". If you skip these tables, it updates the target.

In previous versions, ALMTK closed unexpectedly, now (version 5.0.11), it presents the above error.

Attached, the source and target model.bim files, in addition to the error message print.

Tks,

João Carlos dos Santos
Rio de Janeiro - Brazil

**Comment by christianwade** [comment]
Hi João,

Thanks for raising this. Can you please try the new version 5.0.12? It should be fixed now.

Thanks,
Christian

**Comment by jkapoio** [comment]
thanks for the quick response. I will test and leave feedback here. 
Thank you very much.

**Comment by jkapoio** [comment]
It worked!!! Thank you very much, Chris.

**Comment by christianwade** [comment]
You're welcome!
