### ISSUE TITLE
Description/Annotations change not captured

### ISSUE THREAD

**Issue by spencerclaytonthomas** [microsoft/Analysis-Services#8]
Losing changes to Descriptions/Annotations in the model. You are able to see the difference in the comparison preview but it isn't registered as a change.

**Comment by christianwade** [comment]
Thanks for the suggestion. I had intentionally stripped out annotations since tools like SSDT use them for state things and tend to over-write them at the drop of a hat. Can you elaborate on the scenario? I'd like to confirm it (and then could look into making an option to keep the annotations)?

**Comment by testpatternmih** [comment]
My team uses the annotations to hold metadata/description documentation. If SSDT were to make an override compared to what we have on our production servers we would discard the change. 

Thanks for looking into it!
