### ISSUE TITLE
ALM Toolkit: Error Connecting: The remote server returned an error: (407) Proxy Authentication Required.

### ISSUE THREAD

**Issue by datadu-de** [microsoft/Analysis-Services#85]
Cheers Christian,

this is what I run into when working behind the corporate proxy:
![image](https://user-images.githubusercontent.com/49077745/102252802-d4f34b00-3f06-11eb-920b-03330fb98909.png)

The same thing was already fixed in TabularEditor and DaxStudio, check here for reference:
https://github.com/otykier/TabularEditor/issues/642
https://github.com/DaxStudio/DaxStudio/issues/475

This .net configuration should be added for DefaultCredentials to be used if present

```
<system.net>
    <defaultProxy useDefaultCredentials="true" />
</system.net>

```

Thanks!

**Comment by christianwade** [comment]
Hi, can you try this pre-release and confirm it is working for you?
https://github.com/microsoft/Analysis-Services/releases/tag/5.0.18

Thanks,
Christian

**Comment by datadu-de** [comment]
Hi Christian,
I can confirm, it works with the pre-release 👍 
Thanks and Saúde,
Frank

**Comment by christianwade** [comment]
You're welcome! Obrigado :)
