### ISSUE TITLE
Status Ready vs Status No data

### ISSUE THREAD

**Issue by mbowles201** [microsoft/Analysis-Services#86]
Code that checks ObjectState shows Partitions with 0 rows as Ready and not NoData.  How can we check for 0 rows in a partitions and force it to refresh?

**Comment by christianwade** [comment]
Hi, do you mean in SSMS? You should be able to do this in SSMS

**Comment by mbowles201** [comment]
No.  In the PartitionProcessor.cs file, it sees 0 row, calculated partitions as Ready and I would expect them to show NoData (though MS says NoData is for non-calculated partitions), so how can we detect a 0 row, calculated partition and request a refresh, in code?
