### ISSUE TITLE
Feature request: Option to Wrap text

### ISSUE THREAD

**Issue by rudzimj** [microsoft/Analysis-Services#87]
It would be nice to have an option to wrap text in the comparison view so that I can quickly go through a list of changes without having to scroll horizontally on each one to try to find all of the differences.

Current view:
![image](https://user-images.githubusercontent.com/36211641/103375236-ab5e2600-4aa7-11eb-941c-4e93918aa414.png)

Sample from VS Code that has word wrap:
![image](https://user-images.githubusercontent.com/36211641/103375322-f37d4880-4aa7-11eb-9b5f-ca524ac5e594.png)

**Comment by christianwade** [comment]
Thanks for the suggestion. That control is the typescript based monaco control used by vs code. I didn't write that part (it was written by MAC software). I'll keep that in mind in case I get the opportunity to ask for that change
