### ISSUE TITLE
ALM Toolkit modifications in PBI Service prevents PBIX downloads

### ISSUE THREAD

**Issue by Rian-II** [microsoft/Analysis-Services#88]
Hi Christian,

We have been using a single-dataset-multiple-report architecture while using Sharepoint for version control. We noticed that ALM Toolkit modifies the PBI content when the target is in the PBI service. There's two community posts related to this:
- [Cannot download .pbix after updating dataset with External Tools (XMLA Read/Write)](https://community.powerbi.com/t5/Service/Cannot-download-pbix-after-updating-dataset-with-External-Tools/td-p/1537068)
- [ALM Toolkit error](https://community.powerbi.com/t5/Desktop/ALM-Toolkit-error/m-p/1494655/highlight/true#M619500)

I also see now that there's a [big caution here](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-connect-tools#enhanced-metadata) when using XMLA write operations: _"At this time, a write operation on a dataset authored in Power BI Desktop will prevent it from being downloaded back as a PBIX file. Be sure to retain your original PBIX file."_

**Is this anything that can be prevented by ALM Toolkit or is it something that needs to be managed by the XMLA endpoint write operation? Do you have any idea if this will change in the near future?**

---

_Some non-essential additional info:_
_- Our client no longer allows us to use the desktop versions of O365 apps and has also restricted us from downloading anything from the online O365 apps, which means we can no longer use OneDrive and Sharepoint for version control except if we take the content outside the organisation._
_- This means we need the ability to download from the PBI service with the assumption that it always contains the latest version of PBI content._
_- We're therefore considering using an Azure DevOps implementation for CI/CD and version control._

Lastly, thanks for this great tool called ALM Toolkit. It has improved our way of collaborating on datasets tremendously.

**Comment by christianwade** [comment]
Hi Rian, we'd love to make this work but there is a lot of work to harden Desktop to external changes so it can safely open a PBIX containing a dataset that's been modified outside Desktop. This limitation applies to all XMLA write operations, incremental refresh and large models.

**Comment by DaveRuijter** [comment]
@christianwade you can close this item.

**Comment by collo83** [comment]
Hi Cristian,
is Microsoft working on this topic? Is there any release planning?

Thank you,
Alessandro

**Comment by christianwade** [comment]
Hi Alessandro, not yet. We are still figuring out the plan
