### ISSUE TITLE
Do not summarize numeric columns is not working

### ISSUE THREAD

**Issue by JPpowerbi** [microsoft/Analysis-Services#96]
Hi,

[Formatting]Do not summarize numeric columns is not working.  If I apply the fix it doesn't work because the next time I open tabular editor from the pbix file it shows the same issue.  I also tried applying the script manually but it still doesn't work.

**Comment by christianwade** [comment]
Hi, are you talking about a Tabular Editor issue? If so, please raise it on the TE repo

**Comment by JPpowerbi** [comment]
My issue relates back to this - https://github.com/microsoft/Analysis-Services/tree/master/BestPracticeRules

**Comment by christianwade** [comment]
Got it. Copying @m-kovalsky

**Comment by otykier** [comment]
@JPpowerbi the fix script for this rule sets the `SummarizeBy` column property. By default, Tabular Editor only allows [modelling operations supported by the External Tools integration](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools#supported-write-operations), and unfortunately, changing column properties is not currently among the supported operations.

If you check the "Allow unsupported Power BI features" in Tabular Editor's File > Preferences dialog, Tabular Editor will no longer block these operations, but be advised that you will be making unsupported changes to your PBIX file, which means that Microsoft Support won't be able to help you if something breaks. So make sure to keep a backup of your PBIX file in that case.
