### ISSUE TITLE
M code for tables is missing

### ISSUE THREAD

**Issue by JeroenGeenen** [microsoft/Analysis-Services#97]
I use ALM toolkit to inspect and compare data model for Power BI desktop models. It is great it includes the M expressions for different sources as objects. However, I find that this only works for tables that are not actually loaded into the dataset. If they are, I only get the definition of the data table, but I do not get the M expression of the same name, that is used to upload the table to the database. This is a shame, because this way part of the code is excluded from the comparison.

**Comment by christianwade** [comment]
Hi Jeroen, can you check the partition query for the tables? That's where the M expressions for tables are stored in the AS metadata. You may need to ensure the "Consider query partitions when comparing tables" option is checked.

**Comment by JeroenGeenen** [comment]
Hi Christian, this option was indeed unchecked. I checked it and it is now working as expected. Thanks a lot!

**Comment by christianwade** [comment]
Good to hear!
