### ISSUE TITLE
How do you manage translations life cycle management when the model is modified ?

### ISSUE THREAD

**Issue by didierterrien** [microsoft/Analysis-Services#99]
Hello,
Thank you for this interesting tool. It looks great for the first time we run the translations. How do you manage translations life cycle management when the model is modified ? Do we need to translate the whole model each time and perform a control over each translation even the ones we already corrected ?
Do you plan to translate also visuals strings ?
Regards
Didier Terrien

**Comment by KayUnkroth** [comment]
Hi Didier, the command-line tool (MTCmd) is probably the best choice for ALM. Whenever you modify the model, export all the locales using a small script, perhaps using the same export folder. Existing files will be overwritten. The changes should then be caught by your ALM system. At this point, you have the old translations for objects that still exist in the model plus empty translation fields for new objects in the csv file(s). Using your favorite translation tool, you would then add any missing translations to your csvs, and then re-import. You can choose to keep the old translations or overwrite everything on import. The latter is a good choice if you modified existing translations along with new ones.
Note that the tool can also take an arbitrary list of translations, as long as the CSV format is OK. If the order of the original strings does not match what's in the model, the tool will just look up the string in the csv file and if it finds a perfect match, it will apply the translation. So you could maintain a global list of strings for all your models, and import that whenever a model was modified and new translations were added. Then you'd implement perhaps a separate ALM repo for just the CSVs separate from your models. Maybe you end up with 10,000 or so translated terms. It wouldn't hurt to import those into any new model you create. The tool adds the locales and takes whatever translations it finds. Then export the locales, and check what strings still don't have a translation, add those, and re-import. Done. I think that's the most effective way to go about this.
Hope this helps.
Cheers,
Kay

**Comment by didierterrien** [comment]
Thank you Kay. That's clear !
Regards
